import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {normalize,validateDraws} from '../scripts/sync-lottery.mjs';
const data=JSON.parse(await readFile(new URL('../data/lotto649.json',import.meta.url),'utf8'));
test('published history has at least 500 unique complete draws, ordered newest first',()=>{assert.ok(data.count>=500);assert.equal(data.count,data.draws.length);assert.deepEqual(validateDraws(data.draws),data.draws);assert.equal(createHash('sha256').update(JSON.stringify(data.draws)).digest('hex'),data.sha256);for(const d of data.draws){assert.equal(new Set([...d.numbers,d.special]).size,7);assert.ok([...d.numbers,d.special].every(n=>Number.isInteger(n)&&n>=1&&n<=49));assert.equal(d.prizes.length,8);assert.ok(d.prizes.flat().every(n=>Number.isSafeInteger(n)&&n>=0));}assert.equal(data.coverageEnd,data.draws[0].date);assert.equal(data.coverageStart,data.draws.at(-1).date)});
test('every analysis window counts only six main numbers per draw',()=>{for(const n of [30,60,100,300,500]){const rows=data.draws.slice(0,n);const freq=Array.from({length:49},(_,i)=>rows.filter(d=>d.numbers.includes(i+1)).length);assert.equal(freq.reduce((a,b)=>a+b,0),6*n)}});
test('duplicate and missing periods cannot overwrite published history',()=>{assert.throws(()=>validateDraws([data.draws[0],data.draws[0]]),/Duplicate/);assert.throws(()=>validateDraws([{id:'115000001',date:'2026-01-01'},{id:'115000003',date:'2026-01-09'}]),/Missing/)});
test('normalizer rejects malformed numbers and prize fields',()=>{const row={period:115000001,lotteryDate:'2026-01-01T00:00:00',drawNumberSize:[1,2,3,4,5,6,6]};assert.throws(()=>normalize(row),/Invalid draw/);row.drawNumberSize=[1,2,3,4,5,6,7];assert.throws(()=>normalize(row),/Invalid prize/)});

import {GAMES,validDraw,analyze,shape,matches,generate} from '../app/lottery-engine.mjs';
for(const [key,g] of Object.entries(GAMES)){
 const d=JSON.parse(await readFile(new URL('../data/'+g.file+'.json',import.meta.url),'utf8'));
 test(key+': official history is complete and rule-correct',()=>{assert.equal(d.game,key);assert.ok(d.count>=500);assert.equal(d.count,d.draws.length);assert.deepEqual(validateDraws(d.draws),d.draws);assert.ok(d.draws.every(x=>validDraw(x,g)));assert.equal(createHash('sha256').update(JSON.stringify(d.draws)).digest('hex'),d.sha256);const a=analyze(d.draws.slice(0,500),g,19);assert.equal(a.frequency.reduce((a,b)=>a+b,0),500*g.pick);assert.equal(a.extra.reduce((a,b)=>a+b,0),g.extra?500:0);});
}
const conditions={include:[1,2],exclude:[3,4],odd:'3',low:'',min:'80',max:'180',consecutive:'yes',second:'7'};
test('generated rows obey every condition, avoid duplicates, and keep power second area separate',()=>{let seed=7821;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/2**32};for(const key of ['lotto','power','daily']){const g=GAMES[key],r=generate(g,conditions,19,10,rand);assert.equal(r.rows.length,10);assert.equal(new Set(r.rows.map(d=>JSON.stringify(d))).size,10);for(const d of r.rows){assert.equal(d.numbers.length,g.pick);assert.equal(new Set(d.numbers).size,g.pick);assert.ok(matches(d.numbers,conditions,19));assert.equal(d.special,key==='power'?7:null);}}});
test('impossible and conflicting selections never return relaxed rows',()=>{assert.equal(generate(GAMES.lotto,{...conditions,min:'1000',max:''},19,1).rows.length,0);assert.match(generate(GAMES.lotto,{...conditions,exclude:[1]},19,1).error,/同時/);assert.match(generate(GAMES.lotto,{...conditions,min:'200',max:'100'},19,1).error,/下限/)});
test('known toy draws produce correct gaps, pairs, shapes and repeats',()=>{const g=GAMES.daily,rows=[{numbers:[1,2,3,20,39],special:null},{numbers:[1,5,7,20,38],special:null}];const a=analyze(rows,g,19);assert.equal(a.frequency[0],2);assert.equal(a.gap[4],1);assert.equal(a.gap[3],2);assert.deepEqual(a.repeat,[2]);assert.deepEqual(shape(rows[0].numbers,19),{sum:65,odd:3,low:3,span:38,consecutive:2});assert.deepEqual(a.pairs.find(p=>p[0]==='1・20'),['1・20',2]);});
