// Local acceptance only. Never bundled by production; no real session or account writes.
import React,{useState,useEffect} from 'react';import {createRoot} from 'react-dom/client';
import {trailing} from '../app/quarterly-engine.mjs';
import {PublicSite} from '../app/public-site';import {EquityResearch} from '../app/equity-research';import {COMPANIES,METRICS} from '../app/equity-engine.mjs';import {validateResearchState} from '../app/membership.mjs';
const snapshot={schemaVersion:1,asOf:'2026-09-25',retrievedAt:'2026-09-25T00:00:00Z',companies:COMPANIES.map((c,ci)=>({...c,source:`https://data.sec.gov/api/xbrl/companyfacts/CIK${c.cik}.json`,years:[2025,2024,2023].map((y,i)=>{const start=y+'-01-01',end=y+'-12-31';return {start,end,...Object.fromEntries(Object.entries(METRICS).map(([k,tags],mi)=>[k,{value:(ci+1)*(mi+1)*(4-i)*1e9,start,end,filed:(y+1)+'-02-01',tag:tags[0],accession:'0000000000-26-000001'}]))}})}))};
const quarterly={version:1,asOf:snapshot.asOf,retrievedAt:snapshot.retrievedAt,companies:snapshot.companies.map(c=>{const quarters=[['2025-10-01','2025-12-31'],['2025-07-01','2025-09-30'],['2025-04-01','2025-06-30'],['2025-01-01','2025-03-31']].map(([start,end])=>({start,end,...Object.fromEntries(Object.entries(METRICS).map(([k,tags])=>[k,{start,end,value:1e9,filed:'2026-02-01',accession:'0000000000-26-000001',tag:tags[0],method:'reported'}]))}));return {...c,quarters,ttm:trailing(quarters)}})};
let stored={watchlist:[],saved:[]};
window.fetch=async(url,options)=>{const path=String(url);if(path==='/api/membership')return Response.json({plan:'pro',limits:{watch:200,saved:30},periodEnd:'2099-01-01T00:00:00Z',billingEnabled:false});if(path==='/api/research-state'){if(options?.method==='POST')stored=validateResearchState(JSON.parse(String(options.body)),'pro');return Response.json({state:stored})}if(path.includes('quarterly-'))return Response.json(quarterly);if(path==='/api/research-data'||path==='/api/research-preview')return Response.json(snapshot);return new Response('{}',{status:503})};
function Fixture(){const [page,setPage]=useState('home'),[locale,setLocale]=useState('zh-hant'),[key,setKey]=useState(0),[sizes,setSizes]=useState('');useEffect(()=>{const check=()=>setSizes(document.documentElement.clientWidth+' / '+document.documentElement.scrollWidth);const observer=new ResizeObserver(check);observer.observe(document.body);check();return()=>observer.disconnect()},[]);return <><aside style={{background:'#fff0c5',padding:12,fontSize:12}}>SYNTHETIC ACCEPTANCE FIXTURE · no real session / no account writes<p>Viewport / content width: {sizes}</p><div className="actions" style={{flexWrap:'wrap'}}><button className="btn" onClick={()=>setLocale(locale==='en'?'zh-hant':'en')}>Language</button>{['home','macro','study','markets','digital','lottery','account-tools'].map(x=><button className="btn" onClick={()=>setPage(x)} key={x}>{x}</button>)}<button className="btn" onClick={()=>setKey(x=>x+1)}>Reload component</button></div></aside>{page==='account-tools'?<main style={{padding:16}}><EquityResearch key={key} locale={locale} plan="pro" workspace/></main>:<PublicSite key={page+locale+key} path={`/${locale}/${page==='home'?'':page+'/'}`}/>}</>};createRoot(document.getElementById('root')!).render(<Fixture/>);
