export function uid(){const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;}
export const GAMES = {
 lotto:{name:'大樂透',max:49,count:6,price:50,second:0,combinations:13983816},
 power:{name:'威力彩',max:38,count:6,price:100,second:8,combinations:22085448},
 daily:{name:'今彩 539',max:39,count:5,price:50,second:0,combinations:575757},
};
export type Game=keyof typeof GAMES;
export type Plan={id:string;game:Game;budget:number;numbers:number[][];created:string;note:string};
export type RecordItem={id:string;date:string;game:Game;cost:number;prize:number;note:string};
export type Run={id:string;name:string;version:string;task:string;dataset:string;protocol:string;budget:number;cost:number;prize:number;trials:number;latency:number;status:string;filename?:string;sha256?:string;created:string};
export type Article={id:string;title:string;body:string;published:boolean};
export type Workspace={plans:Plan[];records:RecordItem[];runs:Run[];articles:Article[];audit:{id:string;at:string;action:string}[];monthlyBudget:number;activeRun:string|null;previousRun:string|null};
export const demoDraws=Array.from({length:60},(_,i)=>{const a=Array.from({length:49},(_,j)=>j+1);let x=(i+1)*731;for(let j=a.length-1;j>0;j--){x=(x*1664525+1013904223)>>>0;const k=x%(j+1);[a[j],a[k]]=[a[k],a[j]];}return {id:`DEMO-${String(i+1).padStart(3,'0')}`,numbers:a.slice(0,6).sort((a,b)=>a-b),special:a[6]};});
export const initialWorkspace:Workspace={
 plans:[{id:'plan-demo',game:'lotto',budget:500,numbers:[[3,12,19,27,35,46],[7,14,22,31,38,49]],created:'2026-09-18T10:00:00Z',note:'示範規劃'}],
 records:[{id:'r1',date:'2026-09-04',game:'lotto',cost:300,prize:0,note:'示範紀錄'},{id:'r2',date:'2026-09-08',game:'lotto',cost:200,prize:400,note:'示範紀錄'},{id:'r3',date:'2026-09-11',game:'power',cost:300,prize:0,note:'示範紀錄'},{id:'r4',date:'2026-09-15',game:'daily',cost:200,prize:50,note:'示範紀錄'},{id:'r5',date:'2026-09-18',game:'lotto',cost:200,prize:0,note:'示範紀錄'}],
 runs:[{id:'run-a',name:'Random baseline',version:'1.0.0',task:'lotto',dataset:'DEMO-60-v1',protocol:'equal-budget-v1',budget:500,cost:30000,prize:14200,trials:60,latency:3,status:'正式版本',created:'2026-09-16T09:00:00Z'},{id:'run-b',name:'Frequency model',version:'0.2.0',task:'lotto',dataset:'DEMO-60-v1',protocol:'equal-budget-v1',budget:500,cost:30000,prize:13800,trials:60,latency:18,status:'待驗證',created:'2026-09-18T09:00:00Z'},{id:'run-c',name:'Balanced sampler',version:'0.1.0',task:'lotto',dataset:'DEMO-60-v1',protocol:'equal-budget-v1',budget:500,cost:30000,prize:14600,trials:60,latency:8,status:'待驗證',created:'2026-09-19T09:00:00Z'}],
 articles:[{id:'a1',title:'每一組號碼的中獎機率，都一樣嗎？',body:'公平且獨立的開獎中，每一組合法號碼的機率相同。歷史出現次數是描述統計，不能用來保證下一期結果。',published:true},{id:'a2',title:'先設定預算，再開始分析',body:'將樂透視為娛樂支出。先設定自己可承受的上限，再記錄每次支出與獎金；不要因為虧損提高預算。',published:true}],
 audit:[],monthlyBudget:2000,activeRun:'run-a',previousRun:null,
};
export const emptyWorkspace:Workspace={plans:[],records:[],runs:[],articles:[],audit:[],monthlyBudget:0,activeRun:null,previousRun:null};
function randomInt(n:number){const a=new Uint32Array(1),ceiling=Math.floor(4294967296/n)*n;do{crypto.getRandomValues(a);}while(a[0]>=ceiling);return a[0]%n;}
export function generateNumbers(game:Game,count:number):number[][]{if(!GAMES[game]||!Number.isInteger(count)||count<1||count>100)throw new Error('每次請產生 1–100 注。');const g=GAMES[game],seen=new Set<string>(),result:number[][]=[];while(result.length<count){const pool=Array.from({length:g.max},(_,i)=>i+1);for(let j=pool.length-1;j>0;j--){const k=randomInt(j+1);[pool[j],pool[k]]=[pool[k],pool[j]];}const numbers=pool.slice(0,g.count).sort((a,b)=>a-b);if(g.second)numbers.push(randomInt(g.second)+1);const key=numbers.join(',');if(!seen.has(key)){seen.add(key);result.push(numbers);}}return result;}
export function validateReport(v:unknown):Run{if(!v||typeof v!=='object')throw new Error('請上傳 JSON 物件。');const r=v as Record<string,unknown>;for(const key of ['name','version','task','dataset','protocol'])if(typeof r[key]!=='string'||!(r[key] as string).trim()||(r[key] as string).length>160)throw new Error(`缺少或無效的欄位：${key}`);if(!Object.keys(GAMES).includes(r.task as string))throw new Error('第一版支援 lotto、power、daily 任務。');for(const key of ['budget','cost','prize','trials','latency'])if(typeof r[key]!=='number'||!Number.isFinite(r[key])||(r[key] as number)<0)throw new Error(`無效的數值：${key}`);if((r.cost as number)<=0||(r.budget as number)<=0||!Number.isInteger(r.trials)||(r.trials as number)<1)throw new Error('成本、預算與期數必須大於零，期數須為整數。');return {id:uid(),name:r.name as string,version:r.version as string,task:r.task as string,dataset:r.dataset as string,protocol:r.protocol as string,budget:r.budget as number,cost:r.cost as number,prize:r.prize as number,trials:r.trials as number,latency:r.latency as number,status:'待驗證',created:new Date().toISOString()};}
export function canCompare(runs:Run[]){return runs.length>=2&&runs.every(r=>['task','dataset','protocol','budget','trials'].every(k=>r[k as keyof Run]===runs[0][k as keyof Run]));}
