import {defaultChart,layoutForSaved,MAX_COMPARE} from './research-layout.mjs';
import {instrumentHref,findInstrument} from './instrument-catalog.mjs';
import {createResearchStateClient} from './research-state-client.mjs';
import {useMemberAccess} from './use-member-access';
import {useEffect,useMemo,useState} from 'react';
import {annualFee,ratios,validateEquities,filingURL,COMPANIES} from './equity-engine.mjs';
import {ETFS,ETF_REVIEWED} from './etf-catalog.mjs';
import './equity-research.css';
import {ResearchCharts} from './research-charts';
import {ResearchEvidence} from './research-evidence';
import {ResearchContextComparison} from './research-context';
import {ResearchToolbox} from './research-toolbox';
import {PLANS} from './membership.mjs';
export function EquityResearch({locale='en',plan='free',workspace=false,initialQuery='',focused=false}:{locale?:string;plan?:string;workspace?:boolean;initialQuery?:string;focused?:boolean}){
 const full=plan==='research'||plan==='pro',focusedFund=focused&&findInstrument(initialQuery)?.type==='etf';
 const Title=workspace?'h1':'h2';
 const t=(en:string,zh:string)=>locale==='zh-hant'?zh:en;
 const initialSearch=initialQuery||(typeof window!=='undefined'?new URLSearchParams(window.location.search).get('q')||'':'');
 const initialAsset=findInstrument(initialSearch.trim().toUpperCase());
 const [data,setData]=useState<any>(null),[error,setError]=useState(false),[attempt,setAttempt]=useState(0),[query,setQuery]=useState(initialSearch),[picker,setPicker]=useState(''),[year,setYear]=useState('latest'),[yearFrom,setYearFrom]=useState('all'),[onlyWatch,setOnlyWatch]=useState(false),[watch,setWatch]=useState<string[]>([]),[notice,setNotice]=useState(''),[amount,setAmount]=useState('10000');
 const [selectedFunds,setSelectedFunds]=useState<string[]>(()=>initialAsset?.type==='etf'?[initialAsset.symbol]:['IVV']),[benchmark,setBenchmark]=useState('VTI'),[macroIds,setMacroIds]=useState<string[]>(['us-cpi','us-rate']);
 const [saved,setSaved]=useState<any[]>([]),[saveName,setSaveName]=useState(''),[saving,setSaving]=useState(false),[stateReady,setStateReady]=useState(false),[stateError,setStateError]=useState(false),[stateAttempt,setStateAttempt]=useState(0);
 const stateClient=useMemo(()=>createResearchStateClient(),[]);
 const [chart,setChart]=useState(()=>({...defaultChart(),selected:initialAsset?.type==='stock'?[initialAsset.symbol]:['NVDA']}));
 const [metrics,setMetrics]=useState(['revenue','netIncome','operatingCashFlow']);
 const labels:Record<string,string>={revenue:t('Revenue','營收'),netIncome:t('Net income','淨利'),operatingCashFlow:t('Operating cash flow','營業現金流')};
 useEffect(()=>{let live=true;if(!full)return;setStateReady(false);setStateError(false);stateClient.load().then(state=>{if(live){setWatch(state.watchlist);setSaved(state.saved);setStateReady(true);setNotice('')}}).catch(()=>{if(live){setStateError(true);setNotice(t('Account research could not be reconciled; saving remains disabled. Retry before making another change.','帳號研究資料尚未重新核對，儲存維持停用；請先重試，再進行下一項變更。'))}});return()=>{live=false}},[full,stateAttempt,stateClient]);
 useEffect(()=>{if(full&&stateReady&&new URLSearchParams(window.location.search).get('focus')==='saved')document.getElementById('saved-research')?.scrollIntoView();},[full,stateReady]);
 useEffect(()=>{if(focusedFund)return;const ac=new AbortController();setError(false);setData(null);fetch(full?'/api/research-data':'/api/research-preview',{signal:ac.signal}).then(r=>{if(!r.ok)throw Error('Unavailable');return r.json()}).then(d=>setData(validateEquities(d,{preview:!full}))).catch(e=>{if(e.name!=='AbortError')setError(true)});return()=>ac.abort()},[attempt,full,focusedFund]);
 useEffect(()=>{if(focused)return;const symbol=query.trim().toUpperCase();if(!symbol){setPicker('');return;}const stock=(data?.companies||[]).find((x:any)=>x.symbol===symbol),fund=(full?ETFS:ETFS.slice(0,1)).find(x=>x.symbol===symbol);if(stock)setPicker('stock:'+symbol);else if(fund)setPicker('etf:'+symbol);},[query,data,full,focused]);
 async function saveState(nextWatch:string[],nextSaved:any[]){if(!full||!stateReady||saving)return;setSaving(true);try{const state=await stateClient.save({watchlist:nextWatch,saved:nextSaved});setWatch(state.watchlist);setSaved(state.saved);setStateError(false);setNotice(t('Saved to your account. No notifications were sent.','已儲存到帳號，沒有發送通知。'));}catch{setStateReady(false);setStateError(true);setNotice(t('Save outcome could not be confirmed. Saving is locked until a fresh account read succeeds.','無法確認儲存結果；在重新讀取帳號資料成功前，儲存功能將保持鎖定。'))}finally{setSaving(false)}}
 function toggle(symbol:string){void saveState(watch.includes(symbol)?watch.filter(s=>s!==symbol):[...watch,symbol],saved);}
 const allCompanies:Array<any>=data?.companies||[],availableFunds=full?ETFS:ETFS.slice(0,1),search=query.trim().toLowerCase();
 const companyChoices=allCompanies.filter(c=>(!search||(c.symbol+' '+c.name+' '+(findInstrument(c.symbol)?.aliases||'')).toLowerCase().includes(search))&&(!onlyWatch||watch.includes(c.symbol)));
 const fundChoices=availableFunds.filter(f=>(!search||(f.symbol+' '+f.name+' '+(findInstrument(f.symbol)?.aliases||'')).toLowerCase().includes(search))&&(!onlyWatch||watch.includes(f.symbol)));
 const companies=allCompanies.filter(c=>chart.selected.includes(c.symbol)),funds=availableFunds.filter(f=>selectedFunds.includes(f.symbol));
 const years=[...new Set<string>(allCompanies.flatMap((c:any)=>c.years.map((r:any)=>r.end.slice(0,4))))].sort().reverse();
 const yearInRange=(end:string)=>{const y=end.slice(0,4);return (yearFrom==='all'||yearFrom==='latest'||y>=yearFrom)&&(year==='latest'||y<=year)};
 const comparisonRows=companies.flatMap((company:any)=>company.years.map((row:any,index:number)=>({company,row,index})).filter((x:any)=>yearFrom==='latest'?x.index===0:yearInRange(x.row.end)));
 const selectedSymbols=[...chart.selected,...selectedFunds],scopeFull=selectedSymbols.length>=MAX_COMPARE;
 const autoSaveName=(selectedSymbols.join(' + ')+' · '+(yearFrom==='all'?t('all years','全部年度'):yearFrom)+'–'+(year==='latest'?t('latest','最新'):year)).slice(0,80);
 function addInstrument(){
  if(!picker)return;const [kind,symbol]=picker.split(':');if(!symbol)return;
  if(kind==='stock'){if(!chart.selected.includes(symbol)&&scopeFull){setNotice(t('Compare up to eight instruments. Remove one before adding another.','最多同時比較八個標的，請先移除一個。'));return;}if(!chart.selected.includes(symbol))setChart({...chart,selected:[...chart.selected,symbol]});}
  if(kind==='etf'){if(!selectedFunds.includes(symbol)&&scopeFull){setNotice(t('Compare up to eight instruments. Remove one before adding another.','最多同時比較八個標的，請先移除一個。'));return;}if(!selectedFunds.includes(symbol))setSelectedFunds(v=>[...v,symbol]);}
  setPicker('');setQuery('');setNotice('');
 }
 function removeStock(symbol:string){setChart({...chart,selected:chart.selected.filter((s:string)=>s!==symbol)});}
 function removeFund(symbol:string){setSelectedFunds(v=>v.filter(s=>s!==symbol));}
 function changeYearFrom(value:string){setYearFrom(value);if(value!=='all'&&year!=='latest'&&year<value)setYear(value);}
 function changeYearTo(value:string){setYear(value);if(value!=='latest'&&yearFrom!=='all'&&yearFrom>value)setYearFrom(value);}
 function recentYears(count:number){if(!years.length)return;if(count===1){setYearFrom('latest');setYear('latest');return;}setYearFrom(years[Math.min(count-1,years.length-1)]||'all');setYear('latest');}
 function setStockSelection(symbols:string[]){const max=Math.max(0,MAX_COMPARE-selectedFunds.length);setChart({...chart,sector:'all',selected:symbols.slice(0,max)});}
 const val=(v:number|null|undefined)=>v==null?'—':new Intl.NumberFormat(locale==='zh-hant'?'zh-TW':'en-US',{maximumFractionDigits:1}).format(v/1e9);
 const percent=(v:number|null)=>v==null?'—':v.toFixed(1)+'%';
 const stale=data&&Date.now()-Date.parse(data.retrievedAt)>72*3600000;
 return <div className="equity-research" lang={locale==='zh-hant'?'zh-Hant':'en'}>
 <div className="eq-heading"><div><p className="eyebrow">STOCKS & ETF · SOURCE FIRST</p><Title>{focused?t('Financial research','財務研究'):t('Compare companies, ETFs & market context','比較公司、ETF 與市場背景')}</Title><p>{focused?(focusedFund?t('Fund scope and expense estimates, with issuer sources.','基金投資範圍與費用估算，附發行機構來源。'):t('Company annual financials and chart, with reporting dates and sources.','公司年度財報與圖表，附申報日期及原始來源。')):full?t('Build one scope, compare companies across years, add ETFs, benchmark context and macro evidence, then save the whole research view.','先建立一組比較範圍，跨年度看公司、加入 ETF、大盤與總經背景，再把整個研究畫面保存起來。'):t('Explore NVIDIA’s annual financials and IVV’s costs. No account required.','查看 NVIDIA 年度財報與 IVV 費用，不需帳號。')}</p></div>{workspace?<div className="eq-heading-actions"><a className="btn primary" href={'/'+locale+'/#dashboard'}>{t("Today's Actions",'今日 Actions')}</a><a className="btn" href={'/'+locale+'/study/'}>{t('Guided research','引導式研究')}</a></div>:<a className="btn" href={locale==='zh-hant'?'/en/research/':'/zh-hant/research/'}>{locale==='zh-hant'?'English':'繁體中文'}</a>}</div>
 {!full&&<aside className="eq-notice"><strong>{focused?t('Public preview · ','公開預覽 · ')+initialQuery:t("Public preview · NVIDIA and IVV","公開預覽 · NVIDIA 與 IVV")}</strong><p>{t("Full stock tools require Research or Pro. Subscriptions are not open yet; this preview does not enroll or charge you.","完整股票工具需 Research 或 Pro。訂閱尚未開放，本預覽不會建立訂閱或扣款。")}</p><a href={locale==='zh-hant'?'/zh-hant/library/stock-etf-research/':'/en/library/stock-etf-research/'}>{t('How to read this preview','如何讀懂預覽')}</a> · <a href={locale==='zh-hant'?'/zh-hant/pricing/':'/en/pricing/'}>{t("Compare membership plans","比較會員方案")} →</a></aside>}<details className="eq-legal-details"><summary>{t('Research scope & limits','研究範圍與限制')}</summary><p>{t('Independent factual research, not personalized investment advice or a buy/sell recommendation. Investments can lose value; past results do not guarantee future returns. No real-time prices, trading or price alerts.','獨立事實研究，不是個人化投資建議或買賣推薦。投資可能虧損，歷史結果不保證未來報酬。目前不提供即時報價、交易或價格提醒。')}</p></details>
 {!focused&&<nav className="eq-workspace-nav" aria-label={t('Research sections','研究區段')}><a href="#research-overview">{t('Overview','總覽')}</a><a href="#financials">{t('Financials','財務')}</a><a href="#charts">{t('Charts','圖表')}</a><a href="#market-context">{t('Market & macro','市場與總經')}</a><a href="#funds">ETF</a><a href="#evidence">{t('Sources','證據來源')}</a>{full&&<a href="#saved-research">{t('Saved','已保存')}</a>}</nav>}
 {!focused&&<section className="eq-scope-builder">
  <div className="eq-section-heading"><div><p className="eyebrow">COMPARE SCOPE</p><h2>{t('Build one comparison scope','先建立同一個比較範圍')}</h2><p>{t('Choose companies and ETFs from the data already available, then set a year range. The table, charts, benchmark context and saved research all follow this scope.','直接從目前已有資料選公司與 ETF，再設定年度範圍；表格、圖表、大盤背景與儲存研究都共用同一組選擇。')}</p></div><strong>{selectedSymbols.length} / {MAX_COMPARE}</strong></div>
  <div className="eq-controls">
   <label>{t('Search available data','搜尋已有資料')}<input type="search" value={query} onChange={e=>setQuery(e.target.value)} maxLength={80} placeholder={full?'MSFT, NVIDIA, semiconductor…':'NVDA, NVIDIA, IVV…'}/></label>
   <label>{t('Choose from available data','從已有資料下拉選擇')}<select value={picker} onChange={e=>setPicker(e.target.value)}><option value="">{t('Select a company or ETF','選擇公司或 ETF')}</option><optgroup label={t('Companies','公司')}>{companyChoices.map(c=><option key={c.symbol} value={'stock:'+c.symbol}>{c.symbol} · {c.name}</option>)}</optgroup><optgroup label="ETF / Trust">{fundChoices.map(f=><option key={f.symbol} value={'etf:'+f.symbol}>{f.symbol} · {f.name}</option>)}</optgroup></select></label>
   <button className="btn primary" disabled={!picker} onClick={addInstrument}>{t('Add to comparison','加入比較')}</button>
   {full&&<label className="eq-check"><input type="checkbox" checked={onlyWatch} onChange={e=>setOnlyWatch(e.target.checked)}/>{t('Limit dropdown to watchlist','下拉只顯示觀察清單')} ({watch.length})</label>}
  </div>
  <div className="eq-scope-chips"><span className="eq-chip-label">{t('Selected','已選')}</span>{chart.selected.map((s:string)=><button key={s} type="button" onClick={()=>removeStock(s)}>{s}<small>{t('Company','公司')}</small><b aria-hidden="true">×</b></button>)}{selectedFunds.map(s=><button key={s} type="button" onClick={()=>removeFund(s)}>{s}<small>ETF</small><b aria-hidden="true">×</b></button>)}{selectedSymbols.length===0&&<span>{t('Nothing selected yet.','尚未選擇標的。')}</span>}</div>
  <div className="eq-year-range"><label>{t('From fiscal year','起始財報年度')}<select value={yearFrom} onChange={e=>changeYearFrom(e.target.value)}><option value="all">{t('Earliest available','最早可用年度')}</option><option value="latest">{t('Latest period per company','各公司最新年度')}</option>{[...years].reverse().map(y=><option key={y} value={y}>{y}</option>)}</select></label><span aria-hidden="true">→</span><label>{t('To fiscal year','結束財報年度')}<select value={year} onChange={e=>changeYearTo(e.target.value)}><option value="latest">{t('Latest available per company','各公司最新年度')}</option>{years.map(y=><option key={y} value={y}>{y}</option>)}</select></label><button className="btn" onClick={()=>{setQuery('');setPicker('');setOnlyWatch(false);setYearFrom('all');setYear('latest');setChart({...chart,selected:['NVDA'],sector:'all'});setSelectedFunds(['IVV']);setBenchmark('VTI');setMacroIds(['us-cpi','us-rate'])}}>{t('Reset scope','重設比較範圍')}</button></div>
  <div className="eq-range-presets"><span>{t('Quick range','快速年度')}</span><button type="button" onClick={()=>recentYears(1)}>{t('Latest','最新')}</button><button type="button" onClick={()=>recentYears(3)}>3Y</button><button type="button" onClick={()=>recentYears(5)}>5Y</button><button type="button" onClick={()=>{setYearFrom('all');setYear('latest')}}>{t('All','全部')}</button></div>
  <p className="eq-meta">{t('Tip: search narrows the dropdown only; it no longer silently replaces your comparison. Remove a chip to take an instrument out.','提示：搜尋只會縮小下拉選單，不會偷偷改掉目前比較內容；要移除標的，直接點上方標籤的 ×。')}</p>
 </section>}
 {!focused&&data&&<ResearchToolbox locale={locale} companies={companies} allCompanies={allCompanies} selectedFunds={selectedFunds} yearFrom={yearFrom} yearTo={year} benchmark={benchmark} onSelectStocks={setStockSelection} maxStocks={Math.max(0,MAX_COMPARE-selectedFunds.length)}/>} 
 {focused&&!focusedFund&&<div className="eq-year-range"><label>{t('From fiscal year','起始財報年度')}<select value={yearFrom} onChange={e=>changeYearFrom(e.target.value)}><option value="all">{t('Earliest available','最早可用年度')}</option>{[...years].reverse().map(y=><option key={y} value={y}>{y}</option>)}</select></label><span aria-hidden="true">→</span><label>{t('To fiscal year','結束財報年度')}<select value={year} onChange={e=>changeYearTo(e.target.value)}><option value="latest">{t('Latest available','最新可用年度')}</option>{years.map(y=><option key={y} value={y}>{y}</option>)}</select></label></div>}
 <p role="status" className="eq-meta">{notice||(full?t('Use ☆ to save to your account. Current coverage: 50 companies and 14 ETF / trust profiles.','按 ☆ 儲存到帳號。目前範圍為 50 家公司及 14 檔 ETF／信託資料。'):t('Preview contains three annual periods for one company and one ETF. Account saving requires a paid plan.','預覽提供一家公司的三個年度與一檔 ETF；帳號儲存需付費方案。'))} {full&&stateError&&<button className="btn" disabled={saving} onClick={()=>setStateAttempt(n=>n+1)}>{t('Reconcile account records','重新核對帳號紀錄')}</button>}</p>
{full&&!focused&&<section id="saved-research" className="eq-save-bar">
 <div className="eq-save-copy"><div><p className="eyebrow">SAVE / RESTORE</p><h2>{t('Save this research view','保存目前研究畫面')}</h2><p>{t('Companies, ETFs, years, dimensions, benchmark, macro context and chart settings are saved together.','公司、ETF、年度、維度、大盤、總經背景與圖表設定會一起保存。')}</p></div><strong>{saved.length} / {PLANS[plan].saved}</strong></div>
 <div className="eq-save-actions"><label>{t('Name (optional)','名稱（可留空）')}<input maxLength={80} value={saveName} onChange={e=>setSaveName(e.target.value)} placeholder={autoSaveName}/></label><button className="btn primary" disabled={!stateReady||saving||saved.length>=PLANS[plan].saved||selectedSymbols.length===0} onClick={()=>void saveState(watch,[...saved,{id:crypto.randomUUID(),name:(saveName.trim()||autoSaveName),query,year,metrics,layout:{version:2,onlyWatch,amount,yearFrom,yearTo:year,selectedFunds,benchmark,macroIds,chart}}])}>{saving?t('Saving…','儲存中…'):t('Save research','儲存研究')}</button></div>
 <p className="eq-meta">{stateError?t('Saving is locked until a fresh account read succeeds.','在重新讀取帳號資料成功前，儲存功能維持鎖定。'):!stateReady?t('Loading account research before saving…','正在讀取帳號研究，完成後即可儲存。'):saved.length>=PLANS[plan].saved?t('Saved-research limit reached. Delete an old item before saving another.','已達儲存上限，請先刪除舊研究。'):t('Leave the name blank to generate one from the selected instruments and fiscal range.','名稱留空時，會依標的與財報年度自動命名。')}</p>
 <details className="eq-saved-list"><summary>{t('Saved research','已保存研究')} ({saved.length})</summary>{saved.length===0?<p>{t('No saved research yet.','目前沒有已保存研究。')}</p>:saved.map(s=><div key={s.id} className="eq-saved-row"><span><strong>{s.name}</strong><small>{s.journey?t('Research path and notes','研究路徑與筆記'):s.layout?t('Comparison scope + chart + context','比較範圍＋圖表＋背景'):t('Legacy conditions','舊版條件')}</small></span><button className="btn" onClick={()=>{if(s.journey){window.location.href=`/${locale}/study/?saved=${encodeURIComponent(s.id)}`;return;}setQuery(s.query);setMetrics(s.metrics);const layout=layoutForSaved(s);setOnlyWatch(layout.onlyWatch);setAmount(layout.amount);setYearFrom(layout.yearFrom);setYear(layout.yearTo==='latest'?(s.year||'latest'):layout.yearTo);setSelectedFunds(layout.selectedFunds);setBenchmark(layout.benchmark);setMacroIds(layout.macroIds);setChart(layout.chart);setNotice(t('Research scope, years, context and chart restored.','已還原比較標的、年度、背景與圖表設定。'))}}>{t('Restore','還原')}</button><button className="btn" disabled={saving} onClick={()=>void saveState(watch,saved.filter(x=>x.id!==s.id))}>{t('Delete','刪除')}</button></div>)}</details>
 </section>}
 {!focusedFund&&<section id="financials" className="eq-section"><h2>{t('Company financial comparison','公司財務比較')}</h2><p>{t('USD billions · annual reports only, not the latest quarter or trailing twelve months. Fiscal year-ends differ; compare the exact start and end dates.','單位：十億美元 · 僅年度報告，不是最新季度或近十二個月。各公司會計年度不同，請比較實際起訖日。')}</p>
 <fieldset className="eq-metrics"><legend>{t('Show metrics','顯示指標')}</legend>{Object.keys(labels).map(k=><label key={k}><input type="checkbox" checked={metrics.includes(k)} onChange={()=>setMetrics(m=>m.includes(k)?m.filter(x=>x!==k):[...m,k])}/>{labels[k]}</label>)}</fieldset>
 {error?<div role="alert">{t('Financial data could not be loaded. No substitute figures are displayed.','財報資料載入失敗，不以替代數字填入。')} <button className="btn" onClick={()=>setAttempt(n=>n+1)}>{t('Retry','重試')}</button></div>:!data?<p role="status">{t('Loading SEC financials…','載入 SEC 財報中…')}</p>:<>
 <p className="eq-meta">SEC EDGAR · {t('Retrieved (UTC)','擷取時間（UTC）')} {data.retrievedAt.replace('T',' ').replace('Z','')} {stale&&<strong> · {t('Snapshot over 72 hours old; verify the source.','快照超過 72 小時，請核對來源。')}</strong>}</p>
 {companies.length===0?<p>{t('No company is selected in the comparison scope. Add one from the dropdown above.','目前比較範圍沒有公司，請從上方下拉選單加入公司。')}</p>:comparisonRows.length===0?<p>{t('The selected companies do not have annual periods inside this year range. Widen the range and try again.','所選公司在這個年度範圍內沒有年度財報，請放寬年度範圍。')}</p>:<div className="eq-scroll" tabIndex={0} aria-label={t('Scrollable financial comparison','可捲動的財報比較')}><table><thead><tr><th>{t('Company','公司')}</th><th>{t('Annual period','年度區間')}</th>{metrics.map(k=><th key={k}>{labels[k]}</th>)}<th>{t('Revenue growth','營收年增率')}</th><th>{t('Net margin','淨利率')}</th></tr></thead><tbody>{comparisonRows.map(({company:c,row:r,index:i}:any)=>{const p=ratios(r,c.years[i+1]);return <tr key={c.symbol+r.end}><th>{full&&<button className="eq-star" disabled={!full||!stateReady||saving} aria-label={t('Toggle watchlist ','切換觀察清單 ')+c.symbol} aria-pressed={watch.includes(c.symbol)} onClick={()=>toggle(c.symbol)}>{watch.includes(c.symbol)?'★':'☆'}</button>}<a href={instrumentHref(locale,c.symbol)}>{c.symbol}</a><small>{c.name}</small></th><td><strong>{r.end.slice(0,4)}</strong><small>{r.start}<br/>→ {r.end}</small></td>{metrics.map(k=><td key={k}>{val(r?.[k]?.value)}</td>)}<td>{percent(p.growth)}</td><td>{percent(p.margin)}</td></tr>})}</tbody></table></div>}
 <p className="eq-meta">{t('Growth uses consecutive annual periods with positive prior revenue. Net margin = net income / revenue. — means unavailable, not zero. Facts use the latest available annual filing for each period, including later restatements; they are not a point-in-time backtest dataset.','年增率使用相鄰年度且前期營收為正；淨利率＝淨利／營收。— 表示不可得，不是零。各期採目前可取得的最新年度申報值，可能包含後來重編；不可當作當時已知的回測資料。')}</p>
 <div className="eq-cards">{companies.map((c:any)=><details key={c.symbol} className="eq-card"><summary>{c.symbol} · {t('Annual history & filing sources','年度歷史與申報來源')}</summary><div className="eq-scroll" tabIndex={0}><table><thead><tr><th>{t('Period end','期末')}</th><th>{labels.revenue}</th><th>{labels.netIncome}</th><th>{labels.operatingCashFlow}</th></tr></thead><tbody>{c.years.map((r:any)=><tr key={r.end}><th>{r.end}</th>{Object.keys(labels).map(k=><td key={k}>{r[k]?<a href={filingURL(c.cik,r[k].accession)} target="_blank" rel="noreferrer" title={r[k].tag+' · '+r[k].filed}>{val(r[k].value)} ↗<small>{t('Filed','申報')} {r[k].filed}</small></a>:'—'}</td>)}</tr>)}</tbody></table></div><a href={c.source} target="_blank" rel="noreferrer">{t('SEC source data','SEC 原始資料')} ↗</a></details>)}</div></>}
 </section>}
 {data&&!focusedFund&&<ResearchCharts companies={companies} locale={locale} full={full} year={year} yearFrom={yearFrom} yearTo={year} chart={chart} onChart={setChart}/>}
 {!focused&&<ResearchContextComparison locale={locale} full={full} symbols={selectedSymbols} benchmark={benchmark} onBenchmark={setBenchmark} macroIds={macroIds} onMacroIds={setMacroIds}/>}
 {!focused&&<ResearchEvidence locale={locale} full={full}/>}
 {(!focused||focusedFund)&&<section id="funds" className="eq-section"><h2>{t('ETF scope & annual cost','ETF 範圍與年度費用')}</h2><p>{t('Issuer facts checked','發行機構資料核對日')} {ETF_REVIEWED} · {t('A small comparison set, not an endorsement or ranking. Different exposures are not interchangeable.','小型比較清單，非推薦或排名。投資範圍不同，不能互相視為等價。')}</p>
 <label className="eq-amount">{t('Hypothetical constant holding value (fund currency)','假設全年固定持有市值（基金幣別）')}<input type="number" min="0" max="1000000000" value={amount} onChange={e=>setAmount(e.target.value)}/></label>
 {(amount.trim()===''||annualFee(Number(amount),0)===null)&&<p role="alert">{t('Enter an amount from 0 to 1,000,000,000.','請輸入 0 至 1,000,000,000 的金額。')}</p>}
 {funds.length>0?<><div className="eq-scroll eq-fund-table" tabIndex={0}><table><thead><tr><th>ETF</th><th>{t('Scope','範圍')}</th><th>{t('Benchmark','追蹤指數')}</th><th>{t('Expense ratio','費用率')}</th><th>{t('Estimated annual cost','估算年度費用')}</th></tr></thead><tbody>{funds.map(f=><tr key={f.symbol}><th>{full&&<button className="eq-star" disabled={!full||!stateReady||saving} aria-label={t('Toggle watchlist ','切換觀察清單 ')+f.symbol} aria-pressed={watch.includes(f.symbol)} onClick={()=>toggle(f.symbol)}>{watch.includes(f.symbol)?'★':'☆'}</button>}<a href={instrumentHref(locale,f.symbol)}>{f.symbol}</a><small>{f.name}</small></th><td>{f.scope[locale==='zh-hant'?'zh-hant':'en']}</td><td>{f.benchmark}</td><td>{f.expense==null?'—':f.expense.toFixed(2)+'%'}</td><td>{f.currency} {amount.trim()!==''&&annualFee(Number(amount),f.expense)!==null?annualFee(Number(amount),f.expense)!.toFixed(2):'—'}</td></tr>)}</tbody></table></div><details className="eq-fund-details"><summary>{t('Fund details, risks & source links','基金細節、風險與來源')}</summary><div className="eq-cards">{funds.map(f=><article className="eq-card" key={f.symbol}><h3><a href={instrumentHref(locale,f.symbol)}>{f.symbol} · {f.name}</a></h3><p>{f.scope[locale==='zh-hant'?'zh-hant':'en']}</p><p><strong>{t('Risk','風險')}:</strong> {f.risk[locale==='zh-hant'?'zh-hant':'en']}</p><p>{f.feeNote[locale==='zh-hant'?'zh-hant':'en']}</p><a href={f.url} target="_blank" rel="noreferrer">{t('Issuer details & prospectus','發行機構資料與公開說明書')} ↗</a></article>)}</div></details></>:<p>{!focused?t('No ETF is selected in the comparison scope. Add one from the dropdown above.','目前比較範圍沒有 ETF，請從上方下拉選單加入。'):full?t('This fund is not available in the current comparison data.','目前比較資料沒有這檔基金。'):t('This public preview does not include the selected fund.','公開預覽目前未包含這檔基金。')}</p>}
 <p className="eq-meta">{t('Estimate = constant holding value × annual expense ratio. Fund expenses are reflected in NAV; this is not a separate bill or a return forecast. Excludes commissions, spreads, taxes, currency changes and variation in fund value. Holdings overlap and live prices are not connected.','估算＝全年固定持有市值 × 年度費用率。基金費用反映於淨值，不是另行帳單或報酬預測；未含佣金、買賣價差、稅、匯率與市值變動。持股重疊及即時行情尚未接入。')}</p>
 </section>}
 {!focused&&<ResearchEvidence locale={locale} full={full}/>}
 </div>;
}

export function ResearchEntry({locale='en',workspace=false,initialQuery='',focused=false}:{locale?:string;workspace?:boolean;initialQuery?:string;focused?:boolean}){const m=useMemberAccess(),zh=locale==='zh-hant';return <>{m.status==='error'&&<aside role="alert" className="eq-notice"><strong>{zh?'會員資格查詢失敗':'Membership could not be confirmed'}</strong><p>{zh?'下方只顯示公開預覽，未判定你的方案為 Free。重新確認後才能開啟完整研究。':'Only the public preview is shown below. Your plan has not been classified as Free; retry to access full research.'}</p><button className="btn" onClick={m.retry}>{zh?'重新確認資格':'Retry membership check'}</button></aside>}{m.status==='loading'&&<p role="status">{zh?'確認會員資格中…':'Checking membership…'}</p>}<EquityResearch key={m.status==='ready'?m.access.plan:'preview'} locale={locale} plan={m.status==='ready'?m.access.plan:'free'} workspace={workspace} initialQuery={initialQuery} focused={focused}/></>;}
