import {memberText,memberFormat} from './member-copy.mjs';
import {workspaceText} from './workspace-i18n.mjs';
import {GAMES,validDraw} from './lottery-engine.mjs';
import {LotteryTools} from './lottery-tools';
import {useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
type Draw={id:string;date:string;numbers:number[];special:number|null;prizes:[number,number][]};
type Dataset={game:string;schemaVersion:number;source:string;sourceUrl:string;retrievedAt:string;coverageStart:string;coverageEnd:string;count:number;draws:Draw[]};

const money=(n:number)=>'NT$ '+n.toLocaleString(memberFormat(locale));
export function HistoricalAnalysis({locale='en'}:{locale?:string}){const t=(k:string,v:any={})=>memberText(locale,k,v);const money=(n:number)=>new Intl.NumberFormat(memberFormat(locale),{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(n);
 const [game,setGame]=useState('lotto');const g=GAMES[game],tiers=g.tiers;
 const [data,setData]=useState<Dataset|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[attempt,setAttempt]=useState(0);
 const [count,setCount]=useState(100),[query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(0),[tab,setTab]=useState('distribution');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setData(null);setError('');fetch('/api/lottery/'+g.file,{signal:controller.signal,cache:'no-cache'}).then(async r=>{if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json() as Dataset;if(d.schemaVersion!==1||!Array.isArray(d.draws)||d.count!==d.draws.length||!d.count||!Number.isFinite(Date.parse(d.retrievedAt))||d.game!==game||d.draws.some(x=>!validDraw(x,g)))throw Error('Invalid dataset');setData(d);}).catch(e=>{if(e.name!=='AbortError')setError('history.error');}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[attempt,game]);
 const draws=data?.draws.slice(0,count)||[];
 const filtered=(data?.draws||[]).filter(d=>(!query||d.id.includes(query.trim()))&&(!from||d.date>=from)&&(!to||d.date<=to));
 const totalPages=Math.max(1,Math.ceil(filtered.length/20));
 const rangeError=!!(from&&to&&from>to);
 const stale=data&&Date.now()-Date.parse(data.retrievedAt)>48*60*60*1000;
 function reset(){setQuery('');setFrom('');setTo('');setPage(0)}
 return <><div className="page-heading"><div><div className="eyebrow">LOTTERY ANALYTICS</div><h1>{t('history.title')}</h1><p>{t('history.sub')}</p></div></div>
 <div className="controls-row"><label className="field">{t('planner.game')}<select className="lottery-control" aria-label={t('planner.game')} value={game} onChange={e=>{setGame(e.target.value);reset();setTab("distribution")}}>{Object.entries(GAMES).map(([key,v]:any)=><option key={key} value={key}>{workspaceText(locale,'game.'+key)} · {v.pick} / {v.max}{key==="power"?" + 1 / 8":""}</option>)}</select></label><label className="field">{t('history.count')}<select className="lottery-control" aria-label={t('history.count')} value={count} onChange={e=>setCount(Number(e.target.value))}>{[30,60,100,300,500].map(n=><option key={n} value={n}>{t('history.recent',{count:n})}</option>)}</select></label></div>
 {loading&&<div className="callout" role="status">{t('history.loading')}</div>}{error&&<div className="error-message" role="alert">{t(error)} <button className="btn" onClick={()=>setAttempt(a=>a+1)}>{t('common.retry')}</button></div>}
 {data&&data.game===game&&<><div className="callout" style={{display:'block',marginBottom:20}}><p><strong>{t('history.coverage',{count:data.count,start:data.coverageStart,end:data.coverageEnd})}</strong></p><p className="small"><a className="text-link" href={data.sourceUrl} target="_blank" rel="noreferrer">{t('history.source')}</a> · {t('history.retrieved')}: {new Date(data.retrievedAt).toLocaleString(memberFormat(locale),{timeZone:'Asia/Taipei'})} · Asia/Taipei</p><p className="small">{t('history.latest',{id:data.draws[0].id})}{stale?t('history.stale'):''}</p></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="mb-5 lottery-tabs"><TabsTrigger value="distribution">{t('history.distribution')}</TabsTrigger><TabsTrigger value="history">{t('history.records')}</TabsTrigger><TabsTrigger value="method">{t('history.method')}</TabsTrigger></TabsList>
 <TabsContent value="distribution"><LotteryTools locale={locale} key={game} draws={draws} g={g}/></TabsContent>
 <TabsContent value="history"><section className="panel"><div className="panel-head"><div><h2>{t('history.all')}</h2><p>{t('history.allHint',{count:data.count})}</p></div></div><div className="panel-body"><div className="actions" style={{flexWrap:'wrap',alignItems:'end'}}><label className="field">{t('history.id')}<input aria-label={t('history.id')} placeholder="115000089" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} maxLength={9}/></label><label className="field">{t('history.from')}<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(0)}}/></label><label className="field">{t('history.to')}<input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(0)}}/></label><button className="btn" onClick={reset}>{t('history.clear')}</button></div>{rangeError?<p className="error-message" role="alert">{t('history.rangeError')}</p>:<><p role="status" className="small spaced">{t('history.found',{count:filtered.length,page:page+1,pages:totalPages})}</p>{!filtered.length&&<div className="empty-state"><h3>{t('history.empty')}</h3><p>{t('history.emptyHint')}</p></div>}{filtered.slice(page*20,(page+1)*20).map(d=><article className="article-card" key={d.id}><div className="controls-row"><h3>{t('history.draw',{id:d.id})}</h3><time dateTime={d.date}>{d.date}</time></div><div className="actions" style={{flexWrap:'wrap',margin:'14px 0'}}><span className="small">{t('history.main')}</span><div className="number-row">{d.numbers.map(n=><span className="ball small" key={n}>{String(n).padStart(2,'0')}</span>)}</div><>{g.extra>0&&<><span className="small">{t(game==='power'?'history.second':'history.special')}</span><span className="ball small special">{String(d.special).padStart(2,'0')}</span></>}</></div><details><summary style={{cursor:'pointer',padding:'12px 0',color:'#08715a'}}>{t('history.details')}</summary><div className="table-wrap"><table className="data-table" style={{width:'100%'}}><thead><tr><th>{t('history.tier')}</th><th>{t('history.winners')}</th><th>{t('history.prize')}</th></tr></thead><tbody>{d.prizes.map(([w,p],i)=><tr key={i}><td>{locale==='en'?`${t('history.tier')} ${i+1}`:tiers[i]}</td><td>{w.toLocaleString(memberFormat(locale))}</td><td>{w===0?t('history.noWinner'):money(p)}</td></tr>)}</tbody></table></div><p className="sample-note">{t('history.prizeHint')}</p></details></article>)}<div className="actions spaced"><button className="btn" disabled={page===0} onClick={()=>setPage(p=>p-1)}>{t('history.previous')}</button><button className="btn" disabled={page+1>=totalPages} onClick={()=>setPage(p=>p+1)}>{t('history.next')}</button></div></>}</div></section></TabsContent>
 <TabsContent value="method"><section className="panel"><div className="panel-body"><h2>{t('history.methodTitle')}</h2><p className="spaced">{t('history.rules',{pick:g.pick,max:g.max})}</p><p className="spaced">{t('history.limitations')}</p><p className="spaced">{t('history.personal')}</p></div></section></TabsContent></Tabs></>}
 </>;
}
