import {useEffect,useMemo,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
type Draw={id:string;date:string;numbers:number[];special:number;prizes:[number,number][]};
type Dataset={schemaVersion:number;source:string;sourceUrl:string;retrievedAt:string;coverageStart:string;coverageEnd:string;count:number;draws:Draw[]};
const tiers=['頭獎','貳獎','參獎','肆獎','伍獎','陸獎','柒獎','普獎'];
const money=(n:number)=>'NT$ '+n.toLocaleString('zh-TW');
export function HistoricalAnalysis(){
 const [data,setData]=useState<Dataset|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[attempt,setAttempt]=useState(0);
 const [count,setCount]=useState(100),[query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(0),[tab,setTab]=useState('distribution');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch('/data/lotto649.json',{signal:controller.signal,cache:'no-cache'}).then(async r=>{if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json() as Dataset;if(d.schemaVersion!==1||!Array.isArray(d.draws)||d.count!==d.draws.length||!d.count||!Number.isFinite(Date.parse(d.retrievedAt))||d.draws.some(x=>!/^\d{9}$/.test(x.id)||!Array.isArray(x.numbers)||x.numbers.length!==6||new Set([...x.numbers,x.special]).size!==7||![...x.numbers,x.special].every(n=>Number.isInteger(n)&&n>=1&&n<=49)||x.prizes?.length!==8))throw Error('Invalid dataset');setData(d);}).catch(e=>{if(e.name!=='AbortError')setError('正式資料暫時無法讀取，請稍後重試。此狀態不代表沒有開獎。');}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[attempt]);
 const draws=data?.draws.slice(0,count)||[];
 const frequency=useMemo(()=>Array.from({length:49},(_,i)=>draws.reduce((n,d)=>n+Number(d.numbers.includes(i+1)),0)),[data,count]);
 const filtered=(data?.draws||[]).filter(d=>(!query||d.id.includes(query.trim()))&&(!from||d.date>=from)&&(!to||d.date<=to));
 const totalPages=Math.max(1,Math.ceil(filtered.length/20));
 const rangeError=!!(from&&to&&from>to);
 const stale=data&&Date.now()-Date.parse(data.retrievedAt)>48*60*60*1000;
 function reset(){setQuery('');setFrom('');setTo('');setPage(0)}
 return <><div className="page-heading"><div><div className="eyebrow">LOTTERY ANALYTICS</div><h1>用統計理解，不用直覺猜測。</h1><p>正式大樂透開獎紀錄、獎金明細與歷史分布。</p></div></div>
 <div className="controls-row"><span className="badge">大樂透 · 6 / 49</span><label className="field">分析期數<select aria-label="分析期數" value={count} onChange={e=>setCount(Number(e.target.value))}>{[30,60,100,300,500].map(n=><option key={n} value={n}>最近 {n} 期</option>)}</select></label></div>
 {loading&&<div className="callout" role="status">正在讀取正式開獎資料…</div>}{error&&<div className="error-message" role="alert">{error} <button className="btn" onClick={()=>setAttempt(a=>a+1)}>重新讀取</button></div>}
 {data&&<><div className="callout" style={{display:'block',marginBottom:20}}><p><strong>正式歷史資料 · 共 {data.count} 期</strong> · {data.coverageStart} 至 {data.coverageEnd}</p><p className="small">來源：<a className="text-link" href="https://www.taiwanlottery.com/lotto/result/lotto649/" target="_blank" rel="noreferrer">台灣彩券官方開獎結果 ↗</a> · 最近成功擷取：{new Date(data.retrievedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})}（台北時間）</p><p className="small">最新收錄：第 {data.draws[0].id} 期；日期為開獎日，不是資料抓取日。{stale?'資料已超過 48 小時未成功更新，請以官方最新公告核對。':''}</p></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="mb-5"><TabsTrigger value="distribution">號碼分布</TabsTrigger><TabsTrigger value="history">開獎紀錄與獎金</TabsTrigger><TabsTrigger value="method">機率與方法</TabsTrigger></TabsList>
 <TabsContent value="distribution"><div className="dashboard-columns"><section className="panel"><div className="panel-head"><div><h2>號碼出現頻率</h2><p>實際 {draws.length} 期 · 主號 {draws.length*6} 筆，不含特別號</p><p>{draws.at(-1)?.date} 至 {draws[0]?.date}</p></div></div><div className="panel-body">{draws.length<count&&<p role="status">目前僅有 {draws.length} 期可用，未以示範資料補足。</p>}<div className="heatmap">{frequency.map((n,i)=><div className="heat-cell" key={i} style={{background:`rgba(19,130,92,${.05+n/Math.max(...frequency,1)*.3})`}}><strong>{String(i+1).padStart(2,'0')}</strong><span>{n} 次</span><small>{(n/draws.length*100).toFixed(1)}%</small></div>)}</div><div className="callout spaced">百分比 = 該號碼出現期數 ÷ 分析期數；不是下一期中獎機率。出現較多或較少，不代表下一期較容易開出。</div></div></section><section className="panel"><div className="panel-head"><h2>一注的頭獎機率</h2></div><div className="panel-body"><div className="big-prob">1 / 13,983,816</div><p className="small muted spaced">從 49 個號碼選 6 個，共有 C(49,6) 種組合。公平、獨立開獎下，每組合法主號的機率相同。</p><button className="btn spaced" onClick={()=>setTab('history')}>查看每期獎號與獎金 →</button></div></section></div></TabsContent>
 <TabsContent value="history"><section className="panel"><div className="panel-head"><div><h2>逐期開獎紀錄</h2><p>查詢全部 {data.count} 期；不受上方分析期數限制。最新一期置頂。</p></div></div><div className="panel-body"><div className="actions" style={{flexWrap:'wrap',alignItems:'end'}}><label className="field">期別<input aria-label="查詢期別" placeholder="例如 115000089" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} maxLength={9}/></label><label className="field">開始日期<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(0)}}/></label><label className="field">結束日期<input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(0)}}/></label><button className="btn" onClick={reset}>清除條件</button></div>{rangeError?<p className="error-message" role="alert">開始日期不能晚於結束日期。</p>:<><p role="status" className="small spaced">找到 {filtered.length} 期 · 第 {page+1} / {totalPages} 頁</p>{!filtered.length&&<div className="empty-state"><h3>沒有符合條件的紀錄</h3><p>請確認期別與已收錄日期範圍，或清除條件。</p></div>}{filtered.slice(page*20,(page+1)*20).map(d=><article className="article-card" key={d.id}><div className="controls-row"><h3>第 {d.id} 期</h3><time dateTime={d.date}>{d.date}</time></div><div className="actions" style={{flexWrap:'wrap',margin:'14px 0'}}><span className="small">主號</span><div className="number-row">{d.numbers.map(n=><span className="ball small" key={n}>{String(n).padStart(2,'0')}</span>)}</div><span className="small">特別號</span><span className="ball small special">{String(d.special).padStart(2,'0')}</span></div><details><summary style={{cursor:'pointer',padding:'12px 0',color:'#08715a'}}>查看本期各獎等明細</summary><div className="table-wrap"><table className="data-table" style={{width:'100%'}}><thead><tr><th>獎等</th><th>中獎注數</th><th>每注獎金</th></tr></thead><tbody>{d.prizes.map(([w,p],i)=><tr key={i}><td>{tiers[i]}</td><td>{w.toLocaleString('zh-TW')}</td><td>{w===0?'無人中獎':money(p)}</td></tr>)}</tbody></table></div><p className="sample-note">一般獎項之官方每注獎金，非個人稅後實領；活動加碼與兌獎資格請以官方公告為準。</p></details></article>)}<div className="actions spaced"><button className="btn" disabled={page===0} onClick={()=>setPage(p=>p-1)}>上一頁</button><button className="btn" disabled={page+1>=totalPages} onClick={()=>setPage(p=>p+1)}>下一頁</button></div></>}</div></section></TabsContent>
 <TabsContent value="method"><section className="panel"><div className="panel-body"><h2>資料與分析方法</h2><p className="spaced">每期主號六個、特別號一個，分開保存。主號分布只計主號，不把特別號混入。來源擷取會檢查重複期別、同年度期別連續性、日期、號碼範圍及各獎等欄位；失敗時保留上一份成功資料。</p><p className="spaced">歷史資料供描述統計與研究使用。更多期數不代表可以預測下一期，也不代表模型已經通過樣本外驗證。</p><p className="spaced">本頁是官方開獎結果；你的個人中獎結果仍需核對實際購買的彩券、當期規則與官方公告。產生號碼不代表已購買。</p></div></section></TabsContent></Tabs></>}
 </>;
}
