export const GAMES={
 lotto:{name:'大樂透',max:49,pick:6,extra:49,extraLabel:'特別號',file:'lotto649',endpoint:'Lotto649Result',key:'lotto649Res',start:'2022-01',odds:13983816,tiers:['頭獎','貳獎','參獎','肆獎','伍獎','陸獎','柒獎','普獎'],fields:['jackpotAssign','secondAssign','thirdAssign','fourthAssign','fifthAssign','sixthAssign','seventhAssign','normalAssign']},
 power:{name:'威力彩',max:38,pick:6,extra:8,extraLabel:'第二區',file:'superlotto638',endpoint:'SuperLotto638Result',key:'superLotto638Res',start:'2021-01',odds:22085448,tiers:['頭獎','貳獎','參獎','肆獎','伍獎','陸獎','柒獎','捌獎','玖獎','普獎'],fields:['super638JackpotAssign','super638SecondAssign','super638ThirdAssign','super638FourthAssign','super638FifthAssign','super638SixthAssign','super638SeventhAssign','super638EighthAssign','super638NinthAssign','super638NormalAssign']},
 daily:{name:'今彩 539',max:39,pick:5,extra:0,extraLabel:'',file:'daily539',endpoint:'Daily539Result',key:'daily539Res',start:'2022-01',odds:575757,tiers:['頭獎','貳獎','參獎','肆獎'],fields:['d539JackpotAssign','d539SecondAssign','d539ThirdAssign','d539FourthAssign']}
};
export function validDraw(d,g){return /^\d{9}$/.test(d.id)&&/^\d{4}-\d{2}-\d{2}$/.test(d.date)&&Number.isFinite(Date.parse(d.date))&&new Date(d.date).toISOString().slice(0,10)===d.date&&Array.isArray(d.numbers)&&d.numbers.length===g.pick&&new Set(d.numbers).size===g.pick&&d.numbers.every(n=>Number.isInteger(n)&&n>=1&&n<=g.max)&&(g.extra?Number.isInteger(d.special)&&d.special>=1&&d.special<=g.extra&&(g.file!=='lotto649'||!d.numbers.includes(d.special)):d.special===null)&&Array.isArray(d.prizes)&&d.prizes.length===g.tiers.length&&d.prizes.every(p=>Array.isArray(p)&&p.length===2&&p.every(n=>Number.isSafeInteger(n)&&n>=0))}
export function shape(nums,split){const a=[...nums].sort((a,b)=>a-b);return {sum:a.reduce((a,b)=>a+b,0),odd:a.filter(n=>n%2).length,low:a.filter(n=>n<=split).length,span:a.at(-1)-a[0],consecutive:a.slice(1).filter((n,i)=>n===a[i]+1).length};}
export function analyze(draws,g,split){const frequency=Array(g.max).fill(0),gap=Array(g.max).fill(draws.length),extra=Array(g.extra).fill(0),tails=Array(10).fill(0),pairs=new Map();const shapes=draws.map(d=>shape(d.numbers,split));draws.forEach((d,i)=>{for(const n of d.numbers){frequency[n-1]++;gap[n-1]=Math.min(gap[n-1],i);tails[n%10]++;}if(g.extra)extra[d.special-1]++;for(let a=0;a<d.numbers.length;a++)for(let b=a+1;b<d.numbers.length;b++){const k=[d.numbers[a],d.numbers[b]].sort((a,b)=>a-b).join('・');pairs.set(k,(pairs.get(k)||0)+1)}});return {frequency,gap,extra,tails,shapes,pairs:[...pairs].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,15),repeat:draws.slice(0,-1).map((d,i)=>d.numbers.filter(n=>draws[i+1].numbers.includes(n)).length)};}
export function matches(nums,c,split){const s=shape(nums,split);return c.include.every(n=>nums.includes(n))&&!c.exclude.some(n=>nums.includes(n))&&(c.odd===''||s.odd===Number(c.odd))&&(c.low===''||s.low===Number(c.low))&&(c.min===''||s.sum>=Number(c.min))&&(c.max===''||s.sum<=Number(c.max))&&(c.consecutive==='any'||(s.consecutive>0)===(c.consecutive==='yes'));}
export function validateConditions(c,g){if(c.include.length>g.pick)return '固定號碼超過每注可選數量。';if(c.include.some(n=>c.exclude.includes(n)))return '同一號碼不能同時固定與排除。';if([...c.include,...c.exclude].some(n=>!Number.isInteger(n)||n<1||n>g.max))return '號碼超出此彩種範圍。';if(g.max-c.exclude.length<g.pick)return '剩餘號碼不足以組成一注。';if([c.min,c.max].some(v=>v!==''&&(!Number.isInteger(Number(v))||Number(v)<0)))return '和值請輸入非負整數。';if(c.min!==''&&c.max!==''&&Number(c.min)>Number(c.max))return '和值下限不能大於上限。';return '';}
// Bounded rejection sampling: never loosen constraints or imply an exhaustive search.
export function generate(g,c,split,amount,rand=Math.random){const error=validateConditions(c,g);if(error)return {rows:[],error};const pool=Array.from({length:g.max},(_,i)=>i+1).filter(n=>!c.exclude.includes(n)&&!c.include.includes(n)),seen=new Set(),rows=[];for(let t=0;t<30000&&rows.length<amount;t++){const p=[...pool],nums=[...c.include];for(let i=0;nums.length<g.pick;i++){const j=i+Math.floor(rand()*(p.length-i));[p[i],p[j]]=[p[j],p[i]];nums.push(p[i]);}nums.sort((a,b)=>a-b);if(!matches(nums,c,split))continue;const special=g.file==='superlotto638'?(c.second===''?1+Math.floor(rand()*8):Number(c.second)):null;const key=nums.join(',')+':'+special;if(seen.has(key))continue;seen.add(key);rows.push({numbers:nums,special});}return {rows,error:rows.length<amount?'在本次抽樣上限內僅找到 '+rows.length+' 組；可調整條件後重試，這不代表不存在其他組合。':''};}
