import {useEffect,useState} from 'react';
import {useMemberAccess} from './use-member-access';
import {PLANS} from './membership.mjs';
export function MembershipPanel({locale,status,access,usage,retry,go}:{locale:string;status:string;access:any;usage:any;retry:()=>void;go:(view:any)=>void}){
 const zh=locale==='zh-hant',t=(a:string,b:string)=>zh?b:a,full=status==='ready'&&['research','pro'].includes(access?.plan),plan=status==='ready'?access.plan:null;
 return <><div className="page-heading"><div><p className="eyebrow">MEMBERSHIP</p><h1>{t('Your membership','我的會員方案')}</h1><p>{t('Check your access, saved research limits and what is available today.','確認目前權益、研究儲存配額與實際可用功能。')}</p></div></div>
 <section className="panel panel-body member-summary" aria-live="polite"><div><p className="eyebrow">{t('CURRENT ACCESS','目前權益')}</p><h2>{plan?plan==='free'?'Free':plan==='pro'?'Pro':'Research':status==='demo'?t('Demo · no membership','示範 · 非會員資格'):status==='loading'?t('Checking…','查詢中…'):t('Unable to confirm','無法確認')}</h2><p>{status==='error'?t('Your plan could not be read. No downgrade or zero usage has been assumed.','無法讀取方案；未推定降級或使用量為零。'):t('Subscriptions are not on sale. No checkout, automatic upgrade or charge.','訂閱尚未銷售；未啟用購買、自動升級或扣款。')}</p>{full&&<><p>{t('Access until','權益有效至')} {new Intl.DateTimeFormat(zh?'zh-TW':'en-US',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Taipei'}).format(new Date(access.periodEnd))} · Asia/Taipei</p><p>{access.cancelAtPeriodEnd?t('Renewal canceled. Access continues through this date.','已取消續訂；權益保留至上述期限。'):t('The server checks your effective membership for each protected request.','每次使用受保護服務均由伺服器核對有效資格。')}</p></>}</div><div className="actions"><button className="btn" onClick={retry}>{t('Refresh status','重新確認狀態')}</button><a className="btn" href={`/${locale}/pricing/`}>{t('Compare plans','比較方案')}</a></div></section>
 {full&&<section className="panel panel-body member-usage"><h2>{t('Account research storage','帳號研究儲存')}</h2><div className="member-usage-grid"><p>{t('Watched symbols','觀察標的')}<strong>{usage?.watch??'—'} / {PLANS[plan].watch}</strong></p><p>{t('Saved conditions','儲存條件')}<strong>{usage?.saved??'—'} / {PLANS[plan].saved}</strong></p></div>{!usage&&<p role="status">{t('Usage is not available yet; it has not been treated as zero. Refresh to retry.','使用量尚無可驗證資料，未當作零；可重新確認狀態。')}</p>}<p>{t('Saving research does not subscribe you to notifications. Chart layouts are not yet saved with conditions.','儲存研究不代表訂閱通知；圖表版面尚未隨研究條件保存。')}</p></section>}
 <div className="overview-grid member-feature-grid"><section className="panel panel-body"><span className="badge">Free</span><h2>{t('Lottery workspace','樂透工作台')}</h2><p>{t('Verified free accounts can use all three lottery games, save plans and record actual spending and prizes.','驗證免費帳號可使用三彩種工具、儲存規劃，並記錄實際收支與獎金。')}</p><button className="btn" onClick={()=>go('analysis')}>{t('Open lottery tools','開啟樂透工具')}</button></section><section className="panel panel-body"><span className="badge neutral">{full?'Research / Pro':t('Limited preview','有限預覽')}</span><h2>{t('Stocks & ETFs','股票與 ETF')}</h2><p>{full?t('50 companies, 14 financial dimensions, three ETF comparisons and account saving.','50 家公司、14 個財務維度、三檔 ETF 比較與帳號儲存。'):t('NVIDIA: three annual periods. IVV: scope and fees. Full tools and account saving require effective Research or Pro access.','NVIDIA 三年度財報、IVV 範圍與費用。完整工具與帳號儲存需有效 Research 或 Pro。')}</p><button className="btn primary" onClick={()=>go('equities')}>{full?t('Open research','開啟研究工具'):t('Open stock preview','開啟股票預覽')}</button></section><section className="panel panel-body"><h2>{t('News & events','新聞與事件')}</h2><p>{t('Official SEC filing records. General news, social attention and AI sentiment are not connected or released.','官方 SEC 申報紀錄；一般新聞、社群聲量與 AI 情緒尚未接入或發布。')}</p><button className="btn" onClick={()=>go('news')}>{t('View source events','查看來源事件')}</button></section><section className="panel panel-body"><span className="badge neutral">{t('Not released','尚未發布')}</span><h2>{t('Advanced models & alerts','進階模型與警示')}</h2><p>{t('Pro does not unlock unvalidated models. Advanced backtests, portfolio risk and AI alerts require separate validation before release.','Pro 不會解鎖未驗證模型。進階回測、投資組合風險與 AI 警示須完成各自驗證後才發布。')}</p></section></div>
 <section className="panel panel-body"><h2>{t('Your account and records','帳號與紀錄')}</h2><p>{t('Email verification and paid membership are separate. An administrator role does not grant paid stock access.','Email 驗證與付費資格分開；管理員角色不會自動取得付費股票權益。')}</p><p>{t('Expiry blocks paid tools and new research writes; it does not automatically delete existing research. Data access, retention and billing terms must be finalized before subscriptions open.','到期後停止付費工具與新增研究寫入，不會自動刪除既有研究；資料取回、保存與帳務條款須在開放訂閱前完成。')}</p></section></>;
}
export function MembershipAccount({locale,mode,go}:{locale:string;mode:string;go:(v:any)=>void}){
 const m=useMemberAccess(mode==='member'),[usage,setUsage]=useState<any>(null);
 useEffect(()=>{setUsage(null);if(m.status!=='ready'||m.access?.plan==='free')return;const ac=new AbortController();fetch('/api/research-state',{signal:ac.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{if(!ac.signal.aborted&&Array.isArray(d.state?.watchlist)&&Array.isArray(d.state?.saved))setUsage({watch:d.state.watchlist.length,saved:d.state.saved.length})}).catch(()=>{});return()=>ac.abort()},[m.status,m.access]);
 return <MembershipPanel locale={locale} status={m.status} access={m.access} usage={usage} retry={m.retry} go={go}/>;
}
