import {useMemberAccess} from './use-member-access';
import React,{useEffect,useState} from 'react';
import {newsPreview} from './news-preview.generated.mjs';
import {publishedNews} from './news-articles.mjs';
import {filterNews,safeSECLink} from './news-engine.mjs';
import {COMPANIES} from './equity-engine.mjs';
import './news-hub.css';
export function NewsArticle({locale,item}:{locale:string;item:any}){const zh=locale==='zh-hant',a=item[zh?'zh-hant':'en'];return <article className="public-article"><a href={`/${locale}/news/`}>← {zh?'新聞與事件':'News & events'}</a><p className="eyebrow">{zh?'文章與觀點':'ARTICLES & COMMENTARY'} · {item.market}</p><h1>{a.title}</h1><p className="public-lead">{a.summary}</p><p>{zh?'發布':'Published'} {item.published} · {zh?'更新':'Updated'} {item.updated}</p>{a.sections.map(([h,b]:string[],i:number)=><section key={i}><h2>{h}</h2>{b.split('\n\n').map((p,j)=><p key={j}>{p}</p>)}</section>)}<h2>{zh?'來源':'Sources'}</h2><ul>{item.sources.map((s:any)=><li key={s.url}><a href={s.url} rel="noreferrer">{s.label}</a></li>)}</ul><p>{zh?'事實研究與觀點，不是個人化買賣建議；投資可能虧損。':'Factual research and commentary, not personalized trading advice. Investments can lose value.'}</p></article>}
export function NewsHub({locale='en',member=false}:{locale?:string;member?:boolean}){
 const zh=locale==='zh-hant',t=(a:string,b:string)=>zh?b:a;
 const access=useMemberAccess(member),plan=access.status==='ready'?access.access.plan:'free',checking=member&&access.status==='loading';
 const [error,setError]=useState(false),[loading,setLoading]=useState(false),[attempt,setAttempt]=useState(0),[rows,setRows]=useState<any[]>(newsPreview.documents),[hasMore,setHasMore]=useState(false),[page,setPage]=useState(0),[symbol,setSymbol]=useState('all'),[query,setQuery]=useState('');
 const full=member&&(plan==='research'||plan==='pro');
 useEffect(()=>{if(!full){setRows(newsPreview.documents);return;}const ac=new AbortController();setLoading(true);setRows([]);setError(false);fetch('/api/news-events?'+new URLSearchParams({symbol,page:String(page)}),{signal:ac.signal}).then(async r=>{if(!r.ok)throw Error();const d=await r.json();if(!Array.isArray(d.documents))throw Error();return d}).then(d=>{if(!ac.signal.aborted){setRows(d.documents);setHasMore(d.hasMore)}}).catch(e=>{if(e.name!=='AbortError')setError(true)}).finally(()=>{if(!ac.signal.aborted)setLoading(false)});return()=>ac.abort()},[full,symbol,page,attempt]);
 const visible=filterNews(rows,query,'all');
 const date=(v:string|null)=>v?new Intl.DateTimeFormat(zh?'zh-TW':'en-GB',{dateStyle:'medium',timeZone:'UTC'}).format(new Date(v)):'—';
 return <div className="news-hub"><header className="news-hero"><div><p className="eyebrow">QUANTPATH · NEWS & EVENTS</p><h1>{t('Follow the source. Understand the event.','追蹤來源，理解事件。')}</h1><p className="public-lead">{t('Original articles and official company filings, with dates and evidence you can check.','閱讀原創文章與官方公司申報，核對每一則內容的日期與證據。')}</p></div><aside className="news-scope"><strong>{t('U.S.-listed companies','美國上市公司')}</strong><p>{t('English and Traditional Chinese describe the same market.','英文與繁體中文對應相同市場。')}</p><span>{t('SEC filings · source linked','SEC 申報 · 原始來源')}</span></aside></header>
 <section aria-labelledby="editorial-heading"><div className="news-section-head"><h2 id="editorial-heading">{t('Articles & commentary','文章與觀點')}</h2><a href={`/${locale}/library/`}>{t('Research guides','研究指南')} →</a></div>{publishedNews.length?<div className="news-grid">{publishedNews.map((a:any)=><article className="news-card" key={a.id}><small>{t('Original article','原創文章')} · {a.published}</small><h3><a href={`/${locale}/news/${a.id}/`}>{a[locale].title}</a></h3><p>{a[locale].summary}</p></article>)}</div>:<p className="news-empty">{t('No articles have been published in this section yet. Explore the research guides or the source observations below.','此區尚無已發布文章。你可以先閱讀研究指南，或查看下方的官方來源事件。')}</p>}</section>
 <section aria-labelledby="events-heading"><div className="news-section-head"><h2 id="events-heading">{t('Official filing events','官方申報事件')}</h2><span className="news-tag">{t('Source records · not AI signals','來源紀錄 · 非 AI 訊號')}</span></div>
 {!full&&<div className="news-access"><strong>{t('Public preview · NVIDIA','公開預覽 · NVIDIA')}</strong><p>{t('Up to three recent NVIDIA observations. Broader company records require active Research or Pro access. Subscriptions are not on sale.','最多三筆近期 NVIDIA 觀測。其他公司的完整來源紀錄需有效 Research 或 Pro 資格；訂閱尚未銷售。')}</p><div className="news-actions"><a className="btn" href={member?`/${locale}/pricing/`:`/${locale}/news/#news`}>{member?t('Membership availability','會員方案狀態'):t('Open member events','開啟會員事件頁')}</a><a href={`/${locale}/research/`}>{t('Compare the financial facts','比較財報事實')} →</a></div></div>}
 <p className="news-meta">{full?t('Records read from the research database. Dates are shown in UTC; date-only filings have no inferred time.','來源紀錄讀取自研究資料庫。時間採 UTC；只有日期的申報不補造時間。'):t('Preview snapshot retrieved (UTC): ','預覽快照擷取時間（UTC）：')+newsPreview.retrievedAt}</p>
 <p>{t('A filing date is not necessarily the event date. Historical backfills are not new alerts. These observations are not a comprehensive news feed, social attention, or sentiment analysis.','申報日不一定是事件日；歷史回補不當作新警示。這些觀測不代表完整新聞、社群聲量或情緒分析。')}</p>
 <div className="news-filters">{full&&<label>{t('Company','公司')}<select value={symbol} onChange={e=>{setSymbol(e.target.value);setPage(0);setQuery('')}}><option value="all">{t('All companies','所有公司')}</option>{COMPANIES.map((c:any)=><option key={c.symbol} value={c.symbol}>{c.symbol} · {c.name}</option>)}</select></label>}<label>{t('Search these displayed records','搜尋本頁紀錄')}<input type="search" maxLength={100} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Company, form or keyword','公司、表單或關鍵字')}/></label><button className="btn" onClick={()=>{setQuery('');setSymbol('all');setPage(0)}}>{t('Reset filters','重設篩選')}</button></div>
 {checking||loading?<p role="status">{t('Loading source records…','載入來源紀錄…')}</p>:(error||(member&&access.status==='error'))?<div role="alert" className="news-empty"><p>{t('Source access could not be confirmed. This does not mean there were no filings.','無法確認來源存取狀態，不代表沒有申報。')}</p><button className="btn" onClick={()=>{access.retry();setAttempt(a=>a+1)}}>{t('Retry','重試')}</button><a href={`/${locale}/news/#login`}>{t('Sign in','登入')}</a></div>:<><p role="status" className="news-meta">{t('Displayed records','本頁顯示')}：{visible.length} / {rows.length}{full?' · '+t('Page','頁')+' '+(page+1):''}</p>{visible.length?<div className="news-grid">{visible.map((d:any)=><article className="news-card" key={d.id}><div className="news-card-top"><span className="news-tag">SEC · {d.form||t('Filing','申報')}</span><span>{d.symbols.join(' · ')}</span></div><h3>{safeSECLink(d.url)?<a href={safeSECLink(d.url)!} target="_blank" rel="noreferrer">{d.title} ↗</a>:d.title}</h3><p>{d.summary?.[locale]||t('Read the original filing for details.','詳情請回查原始申報。')}</p><dl><div><dt>{t('Filed','申報日')}</dt><dd>{date(d.publishedOn)}</dd></div><div><dt>{t('Reported date / period end','報告日期／期末')}</dt><dd>{date(d.eventOn)}</dd></div><div><dt>{t('First recorded · UTC','首次記錄 · UTC')}</dt><dd>{d.firstSeenAt||'—'}</dd></div></dl>{d.backfill&&<small>{t('Historical backfill · no new-event alert','歷史回補 · 不發新事件警示')}</small>}</article>)}</div>:<div className="news-empty"><h3>{t('No matching records','沒有符合的紀錄')}</h3><p>{t('Clear the keyword or select another company. Missing observations are not zero market activity.','清除關鍵字或改選公司；缺少觀測不代表市場活動為零。')}</p><button className="btn" onClick={()=>{setQuery('');setSymbol('all');setPage(0)}}>{t('Show available records','顯示可用紀錄')}</button></div>}{full&&<div className="news-actions"><button className="btn" disabled={page===0} onClick={()=>{setPage(p=>p-1);setQuery('')}}>{t('Previous','上一頁')}</button><button className="btn" disabled={!hasMore} onClick={()=>{setPage(p=>p+1);setQuery('')}}>{t('Next','下一頁')}</button></div>}</>}
 </section><aside className="news-footnote"><strong>{t('Interpretation has limits','解讀有其限制')}</strong><p>{t('General news feeds and social sources are not connected. AI classifications and member alerts are not released. Publishing an article does not validate a model. No buy/sell signals or guaranteed returns.','一般新聞與社群來源尚未接入，AI 分類與會員警示尚未發布。文章發布不等於模型驗證；不提供買賣訊號或保證報酬。')}</p></aside></div>
}
