import {PLANS} from './membership.mjs';
export function Pricing({locale='en'}:{locale?:string}){
 const zh=locale==='zh-hant',t=(en:string,cn:string)=>zh?cn:en;
 const rows=[{id:'free',name:'Free',status:t('Available now','目前可用'),intro:t('Free lottery research after verified sign-in.','完成驗證並登入後，免費使用樂透研究。'),features:[t('Lotto 6/49, Power Lottery and Daily 539','大樂透、威力彩、今彩 539'),t('Historical results, multidimensional analysis and conditional number selection','歷史開獎、多維分析與條件選號'),t('Personal plans and records','個人規劃與紀錄'),t('Limited stock/ETF preview','指定股票／ETF 預覽')]},{id:'research',name:'Research',status:t('Planned · subscriptions not open','規劃方案 · 尚未開放訂閱'),intro:t('Company and ETF research you can save and revisit.','可儲存、比較及持續追蹤的公司與 ETF 研究。'),features:[t('Everything in Free','包含 Free 全部功能'),t('Financial trends, multi-condition screening and comparisons','財報趨勢、多條件篩選與比較'),t('ETF scope and expense comparison','ETF 範圍與費用比較'),t('30 watched symbols · 5 saved conditions','30 個觀察標的 · 5 組儲存條件'),t('Standard results and export','標準結果與匯出')]},{id:'pro',name:'Pro',status:t('In development · subscriptions not open','開發規劃中 · 尚未開放訂閱'),intro:t('Deeper comparison and reproducible model evaluation.','更深入的比較與可重現模型驗證。'),features:[t('Everything in Research','包含 Research 全部功能'),t('Multi-factor analysis and portfolio risk','多因子分析與投資組合風險'),t('Scenario analysis and validated backtesting','情境分析與經驗證的策略回測'),t('200 watched symbols · 30 saved conditions','200 個觀察標的 · 30 組儲存條件'),t('Advanced reports with versions, assumptions and limitations','附版本、假設及限制的進階報告')]}];
 return <><p className="public-lead">{t('One free membership. Two research plans.','一個免費會員，兩個付費研究方案。')}</p><div className="public-note"><strong>{t('Free is available. Research and Pro are not on sale yet.','Free 已開放；Research 與 Pro 尚未開始銷售。')}</strong><p>{t('Prices below are the planned monthly launch prices in USD. No card is collected, no trial converts to a subscription, and no payment is taken. Paid features below describe the release target, not a claim that they are all available today.','以下為預定推出的美元月費。目前不收信用卡、不會由試用轉為訂閱，也不扣款。付費功能列示的是推出目標，不代表目前已全部可用。')}</p></div><div className="public-grid">{rows.map(r=><article className="public-card" key={r.id}><p className="eyebrow">{r.status}</p><h2>{r.name}</h2><p style={{fontSize:32,fontWeight:700}}>US${PLANS[r.id].price}<small style={{fontSize:15,fontWeight:400}}> / {t('month','月')}</small></p><p>{r.intro}</p><ul style={{paddingLeft:20,lineHeight:2}}>{r.features.map(f=><li key={f}>{f}</li>)}</ul>{r.id==='free'?<><a className="btn primary" href={`/${locale}/pricing/#signup`}>{t('Create a free account','建立免費帳號')}</a><p><a href={`/${locale}/pricing/#login`}>{t('Already a member? Sign in','已有帳號？登入')}</a></p></>:<button className="btn" disabled>{t('Not open for purchase','尚未開放購買')}</button>}</article>)}</div>
 <section className="public-note"><h2>{t('What is ready today?','目前實際完成什麼？')}</h2><p>{t('Three lottery games are available to signed-in members. Stock research currently covers 50 companies and three ETFs; the public preview shows NVIDIA and IVV. Account entitlement checks and research saving are built, but paid membership sales remain closed.','已登入會員可使用三個彩種。目前股票研究範圍為 50 家公司及三檔 ETF；公開預覽僅展示 NVIDIA 與 IVV。帳號權限及研究儲存已建置，付費會員仍未開始銷售。')}</p><a href={zh?'/zh-hant/research/':'/en/research/'}>{t('Explore the public preview','查看公開預覽')} →</a></section>
 <section className="public-note"><h2>{t('Before paid launch','開始收費前')}</h2><p>{t('Research requires verified coverage of at least 30 companies and 10 ETFs, usable screening and export, account saving, payment/cancellation testing and review of data rights and applicable regulation. Pro opens only after its advanced tools and evaluations are delivered.','Research 須完成至少 30 家公司及 10 檔 ETF 的資料驗證、可用的篩選與匯出、帳號儲存、付款與取消測試，以及資料權利和適用法規審查。Pro 須在進階工具與驗證完成後才開放。')}</p><p>{t('Planned billing: monthly only, no annual commitment or lifetime plan. Cancellation stops future renewal; paid access continues until the paid-through date, then returns to Free. Research records are retained under the published retention policy; limits may require reducing saved items before editing after a downgrade. Final tax, refund and billing terms will be shown before checkout is enabled.','預定採月繳，不綁年約、不提供終身方案。取消後不再續訂，已付費權益保留到期限結束，之後回到 Free。研究紀錄依正式保存政策保留；降級後若超出上限，需先減少保存項目再編輯。金流開放前會公布稅費、退款及完整帳務條款。')}</p></section>
 <section className="public-note"><h2>{t('Research and responsible use','研究與責任使用')}</h2><p>{t('Higher tiers provide more tools, not guaranteed accuracy or returns. Lottery results are independent under the stated assumptions; historical frequencies do not improve the next draw’s odds. Stock tools do not reuse lottery probability assumptions. Investments can lose value. No trading, ticket sales, proxy betting or guaranteed-return services.','較高方案提供更多工具，不承諾更準確或保證收益。樂透在所述假設下為獨立開獎，歷史頻率不提高下一期機率；股票工具不沿用樂透的機率假設。投資可能虧損。本站不提供交易、彩券銷售、代購投注或保證獲利服務。')}</p></section></>;
}
