// Public editorial catalog. Never store member records or private analytics here.
export const categories = {
 investing: {en:'Stocks & ETF', 'zh-hant':'股票與 ETF'},
 probability: {en:'Probability', 'zh-hant':'機率入門'},
 planning: {en:'Planning', 'zh-hant':'預算規劃'},
 models: {en:'Model evaluation', 'zh-hant':'模型評估'}
};
export const catalog = [
 {id:'independent-draws',category:'probability',market:'global',updated:'2026-09-20',status:'published',version:1,
 en:{title:'What past draws can—and cannot—tell you',summary:'Separate historical frequency from the probability of the next independent draw.',sections:[['Start with the assumptions','If draws are fair and independent, a number being frequent or absent in past draws does not change its probability in the next draw. A frequency chart describes the sample you selected; it does not establish predictive advantage.'],['A small example','For a fair six-sided die, the probability of a six on the next roll is 1/6, even after five rolls without a six. Independence is the key assumption. This is a teaching example, not an audit of any lottery.'],['Read a chart carefully','Check the source, sample size, date range, rules and treatment of special numbers. Investigate missing or duplicate records before interpreting a pattern. QuantPath labels the official source and retrieval time of its draw history. Demo model results remain synthetic.']]},
 'zh-hant':{title:'歷史開獎能告訴你什麼？',summary:'區分歷史出現次數與下一次獨立開獎的機率。',sections:[['先確認前提','如果開獎公平且各次相互獨立，某個號碼過去經常出現或長期未出現，都不會改變下一次的機率。頻率圖描述的是你選定的樣本，不能單憑它證明預測優勢。'],['一個簡單例子','公平六面骰下一次擲出六的機率是 1/6，即使前五次都沒有出現六也一樣。關鍵前提是獨立性。這是教學例子，不是對任何彩券的稽核結果。'],['如何閱讀圖表','先看來源、樣本量、日期區間、規則與特別號的處理方式。解讀模式前先排查遺漏與重複紀錄。QuantPath 在開獎紀錄中標示官方來源與擷取時間；示範模型結果仍為合成資料。']]},sources:[{label:'OpenStax · Independent and mutually exclusive events',url:'https://openstax.org/books/introductory-statistics-2e/pages/3-2-independent-and-mutually-exclusive-events'}]},
 {id:'budget-before-results',category:'planning',market:'global',updated:'2026-09-20',status:'published',version:1,
 en:{title:'Record the budget before the outcome',summary:'Use a simple ledger to make costs and outcomes visible.',sections:[['Set a limit first','Choose a discretionary amount that does not compete with essential expenses. Record that limit before generating combinations. A budget is a spending constraint, not a target you must use up.'],['Keep the arithmetic visible','In an illustrative ledger, a budget of 100 units and spending of 30 leave 70 units. If the recorded prize is 5, the net result is 5 − 30 = −25 units. Remaining budget and profit are different quantities.'],['Review without chasing losses','Record the actual date, cost and prize in the same currency. Check duplicate entries and corrections. Review the total before deciding whether to continue; a loss does not make a future win more likely. Current workspace examples use TWD and Taiwan game rules.']]},
 'zh-hant':{title:'先記預算，再看結果',summary:'用簡單的紀錄，把成本與結果分清楚。',sections:[['先設定上限','選擇不影響必要生活支出的可支配金額，並在產生組合前記下上限。預算是支出的限制，不是必須花完的目標。'],['讓計算可以核對','假設預算 100 單位、已支出 30，剩餘預算為 70。若登錄獎金為 5，淨結果就是 5 − 30 = −25 單位。剩餘預算與獲利是不同概念。以上為教學示例。'],['定期檢查，不追逐損失','以相同幣別記錄實際日期、支出與獎金，排查重複紀錄並保留更正。決定是否繼續前先檢查總額；過去虧損不會提高未來中獎機率。目前工作台示例使用新台幣與台灣遊戲規則。']]},sources:[]},
 {id:'compare-models-fairly',category:'models',market:'global',updated:'2026-09-20',status:'published',version:1,
 en:{title:'Compare models under the same conditions',summary:'A report approval is not an independently reproduced experiment.',sections:[['Freeze the comparison','Record the task, dataset version, split dates, baseline, evaluation rules, budget and number of trials before comparing candidates. Keep a held-out set separate from model selection.'],['Make a result reproducible','Preserve code and model versions, random seeds, inputs, evaluation configuration and results. Report the metric definition and uncertainty. A favorable backtest can reflect chance, data leakage or repeated selection.'],['Understand the current lab','The workspace can import and compare JSON reports. Its verification action records an administrator’s review; it does not rerun a model. Publishing changes a version pointer, not a production inference service. Synthetic demo results are not measured model performance.']]},
 'zh-hant':{title:'在相同條件下比較模型',summary:'核准報告，不等於已獨立重現實驗。',sections:[['固定比較條件','比較候選模型前，先記錄任務、資料版本、切分日期、基準、評估規則、預算與試驗次數。保留未參與模型選擇的測試集。'],['讓結果能重現','保存程式與模型版本、隨機種子、輸入、評估設定及結果，說明指標定義與不確定性。看似較好的回測，可能來自隨機波動、資料洩漏或重複挑選。'],['理解目前實驗室','工作台可匯入並比較 JSON 報告。「確認驗證」記錄管理員審核，不會重新執行模型。「發布」切換版本指標，不會部署正式推論服務。合成示範結果不是真實模型績效。']]},sources:[{label:'scikit-learn · Common pitfalls and recommended practices',url:'https://scikit-learn.org/stable/common_pitfalls.html'}]}
];
catalog.push({id:'sports-research',category:'models',market:'global',updated:'2026-09-20',status:'published',version:1,
en:{title:'Sports research: assumptions, evidence and responsible use',summary:'Explore a football scenario calculator, its limits and the safeguards needed before live data.',sections:[['Available now','The sports workspace offers a Poisson football scenario calculator using user-entered hypothetical expected goals. It is not trained on real matches and does not provide validated forecasts, real fixtures or odds. Open the tools page to enter the workspace.'],['Scope and limits','QuantPath Labs is an independent education and research website, not an official lottery partner or betting operator. It does not accept bets or money, sell or purchase tickets, pay prizes or refer users to gambling platforms. Scenario probabilities are not betting advice and do not guarantee outcomes or profits.'],['Responsible use','Do not borrow, chase losses or use essential living funds to gamble. Minors must not purchase or redeem Taiwan sports lottery tickets. If gambling affects your finances or wellbeing, stop and seek qualified support. Local restrictions vary; this notice is not an operating licence or a worldwide legal clearance.'],['Data before forecasts','Live data remains disabled until source use and display rights are verified. Real predictions require timestamped features, chronological evaluation, calibration and reproducible evidence. Historical results alone do not establish future profitability.']]},
'zh-hant':{title:'運動分析：假設、證據與責任使用',summary:'了解足球情境計算器的用途、限制與接入真實資料前的要求。',sections:[['目前可用功能','運動工作台提供 Poisson 足球情境計算器，使用自行輸入的假設預期進球。模型尚未以真實比賽訓練，不提供已驗證預測、真實賽程或賠率。可從工具頁進入工作台。'],['服務範圍與限制','QuantPath Labs 為獨立教育與研究網站，非運彩官方合作平台或投注業者。不收受投注與款項、不銷售或代購彩券、不兌獎，也不導流至博彩平台。情境機率不是投注建議，不保證賽果或獲利。'],['責任使用','勿借貸、追損或挪用生活費投注。未成年人不得購買或兌領台灣運動彩券。若投注影響財務或身心，請停止並尋求合格專業協助。各地規範不同；本警語不是營運許可，也不是全球合法性的保證。'],['先有資料，再談預測','來源使用與公開展示權未確認前，不啟用真實資料。正式預測需要帶時間的特徵、時間順序驗證、機率校準及可重現證據。歷史結果不能單獨證明未來獲利。']]},sources:[{label:'運動彩券發行條例 / Taiwan Sports Lottery Issuance Act',url:'https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=H0120050'}]});
catalog.unshift({"id": "stock-etf-research", "category": "investing", "market": "global", "updated": "2026-09-20", "status": "published", "version": 1, "en": {"title": "Compare company financials and ETF costs", "summary": "Use the research tool to compare annual reports, fund exposure and fees with traceable sources.", "sections": [["Start with the actual figures", "Open Stocks & ETF research for NVIDIA, Microsoft and AMD annual revenue, net income and operating cash flow. Each figure links to its SEC filing. The initial universe is deliberately small and is not a recommendation or a market-wide ranking."], ["Compare dates before growth", "Select a period-ending year and inspect the exact annual start and end dates. A fiscal year ending in January differs from one ending in June. Growth requires adjacent annual periods; missing data is not zero. Later restatements can change historical figures, so this snapshot cannot establish what an investor knew at an earlier date."], ["Compare fund exposure as well as fees", "IVV tracks the S&P 500; ITOT covers the total U.S. equity market; IXUS covers developed and emerging-market equities outside the U.S. The tool shows the issuer expense ratios checked on September 20, 2026 and a simple cost estimate for a constant hypothetical holding. These funds have different exposures, and lower fees alone do not establish suitability."], ["Save research without confusing it with a trade", "The star button saves a symbol in this browser only. There is no account synchronization, automated message, trade execution or price forecast. Investments can lose value. Verify the current issuer prospectus and original financial reports before making a decision."]]}, "zh-hant": {"title": "比較公司財報與 ETF 費用", "summary": "以可回查的來源，比較年度財報、基金投資範圍與費用。", "sections": [["先看實際數據", "開啟股票與 ETF 研究，即可查看 NVIDIA、Microsoft、AMD 的年度營收、淨利與營業現金流，每個數字均可回查 SEC 申報。初始範圍刻意保持精簡，並非投資推薦或全市場排名。"], ["比較成長率之前先比較日期", "選擇財報期末所在年份，核對完整年度起訖日。一月結束的會計年度與六月結束的年度不同。年增率須使用相鄰年度，缺值不是零。後續重編可能改變歷史數字，因此本快照不能證明投資人在過去某日已知哪些資訊。"], ["同時比較基金範圍與費用", "IVV 追蹤 S&P 500；ITOT 涵蓋美國整體股票市場；IXUS 涵蓋美國以外已開發及新興市場股票。工具列出 2026-09-20 核對的發行機構費率，並以假設固定持有市值估算費用。三者投資範圍不同，費用較低不等於適合每位使用者。"], ["區分研究清單與實際交易", "星號僅將標的存入此瀏覽器，不會同步帳號、寄送通知、執行交易或預測股價。投資可能虧損，決策前應核對最新公開說明書與原始財報。"]]}, "sources": [{"label": "SEC · Company Facts API", "url": "https://www.sec.gov/search-filings/edgar-application-programming-interfaces"}, {"label": "iShares · IVV", "url": "https://www.ishares.com/us/products/239726/ishares-core-sp-500-etf"}, {"label": "iShares · ITOT", "url": "https://www.ishares.com/us/products/239724/ishares-core-sp-total-us-stock-market-etf"}, {"label": "iShares · IXUS", "url": "https://www.ishares.com/us/products/244048/ishares-core-msci-total-international-stock-etf"}]});
export const articles=catalog.filter(a=>a.status==='published');
export const pages=['','research','library','tools','methodology','about',...articles.map(a=>'library/'+a.id)];
export function publicRoute(path){const m=path.match(/^\/(en|zh-hant)(?:\/(.*?))?\/?$/);return m&&pages.includes(m[2]||'')?{locale:m[1],page:m[2]||''}:path==='/'?{locale:'en',page:''}:null;}
