// Public editorial catalog. Never store member records or private analytics here.
export const categories = {
 probability: {en:'Probability', 'zh-hant':'機率入門'},
 planning: {en:'Planning', 'zh-hant':'預算規劃'},
 models: {en:'Model evaluation', 'zh-hant':'模型評估'}
};
export const catalog = [
 {id:'independent-draws',category:'probability',market:'global',updated:'2026-09-20',status:'published',version:1,
 en:{title:'What past draws can—and cannot—tell you',summary:'Separate historical frequency from the probability of the next independent draw.',sections:[['Start with the assumptions','If draws are fair and independent, a number being frequent or absent in past draws does not change its probability in the next draw. A frequency chart describes the sample you selected; it does not establish predictive advantage.'],['A small example','For a fair six-sided die, the probability of a six on the next roll is 1/6, even after five rolls without a six. Independence is the key assumption. This is a teaching example, not an audit of any lottery.'],['Read a chart carefully','Check the source, sample size, date range, rules and treatment of special numbers. Investigate missing or duplicate records before interpreting a pattern. QuantPath labels the official source and retrieval time of its draw history. Demo model results remain synthetic.']]},
 'zh-hant':{title:'歷史開獎能告訴你什麼？',summary:'區分歷史出現次數與下一次獨立開獎的機率。',sections:[['先確認前提','如果開獎公平且各次相互獨立，某個號碼過去經常出現或長期未出現，都不會改變下一次的機率。頻率圖描述的是你選定的樣本，不能單憑它證明預測優勢。'],['一個簡單例子','公平六面骰下一次擲出六的機率是 1/6，即使前五次都沒有出現六也一樣。關鍵前提是獨立性。這是教學例子，不是對任何彩券的稽核結果。'],['如何閱讀圖表','先看來源、樣本量、日期區間、規則與特別號的處理方式。解讀模式前先排查遺漏與重複紀錄。QuantPath 在開獎紀錄中標示官方來源與擷取時間；示範模型結果仍為合成資料。']]},sources:[{label:'OpenStax · Independent and mutually exclusive events',url:'https://openstax.org/books/introductory-statistics-2e/pages/3-2-independent-and-mutually-exclusive-events'}]},
 {id:'budget-before-results',category:'planning',market:'global',updated:'2026-09-20',status:'published',version:1,
 en:{title:'Record the budget before the outcome',summary:'Use a simple ledger to make costs and outcomes visible.',sections:[['Set a limit first','Choose a discretionary amount that does not compete with essential expenses. Record that limit before generating combinations. A budget is a spending constraint, not a target you must use up.'],['Keep the arithmetic visible','In an illustrative ledger, a budget of 100 units and spending of 30 leave 70 units. If the recorded prize is 5, the net result is 5 − 30 = −25 units. Remaining budget and profit are different quantities.'],['Review without chasing losses','Record the actual date, cost and prize in the same currency. Check duplicate entries and corrections. Review the total before deciding whether to continue; a loss does not make a future win more likely. Current workspace examples use TWD and Taiwan game rules.']]},
 'zh-hant':{title:'先記預算，再看結果',summary:'用簡單的紀錄，把成本與結果分清楚。',sections:[['先設定上限','選擇不影響必要生活支出的可支配金額，並在產生組合前記下上限。預算是支出的限制，不是必須花完的目標。'],['讓計算可以核對','假設預算 100 單位、已支出 30，剩餘預算為 70。若登錄獎金為 5，淨結果就是 5 − 30 = −25 單位。剩餘預算與獲利是不同概念。以上為教學示例。'],['定期檢查，不追逐損失','以相同幣別記錄實際日期、支出與獎金，排查重複紀錄並保留更正。決定是否繼續前先檢查總額；過去虧損不會提高未來中獎機率。目前工作台示例使用新台幣與台灣遊戲規則。']]},sources:[]},
 {id:'compare-models-fairly',category:'models',market:'global',updated:'2026-09-20',status:'published',version:1,
 en:{title:'Compare models under the same conditions',summary:'A report approval is not an independently reproduced experiment.',sections:[['Freeze the comparison','Record the task, dataset version, split dates, baseline, evaluation rules, budget and number of trials before comparing candidates. Keep a held-out set separate from model selection.'],['Make a result reproducible','Preserve code and model versions, random seeds, inputs, evaluation configuration and results. Report the metric definition and uncertainty. A favorable backtest can reflect chance, data leakage or repeated selection.'],['Understand the current lab','The workspace can import and compare JSON reports. Its verification action records an administrator’s review; it does not rerun a model. Publishing changes a version pointer, not a production inference service. Synthetic demo results are not measured model performance.']]},
 'zh-hant':{title:'在相同條件下比較模型',summary:'核准報告，不等於已獨立重現實驗。',sections:[['固定比較條件','比較候選模型前，先記錄任務、資料版本、切分日期、基準、評估規則、預算與試驗次數。保留未參與模型選擇的測試集。'],['讓結果能重現','保存程式與模型版本、隨機種子、輸入、評估設定及結果，說明指標定義與不確定性。看似較好的回測，可能來自隨機波動、資料洩漏或重複挑選。'],['理解目前實驗室','工作台可匯入並比較 JSON 報告。「確認驗證」記錄管理員審核，不會重新執行模型。「發布」切換版本指標，不會部署正式推論服務。合成示範結果不是真實模型績效。']]},sources:[{label:'scikit-learn · Common pitfalls and recommended practices',url:'https://scikit-learn.org/stable/common_pitfalls.html'}]}
];
export const articles=catalog.filter(a=>a.status==='published');
export const pages=['','library','tools','methodology','about',...articles.map(a=>'library/'+a.id)];
export function publicRoute(path){const m=path.match(/^\/(en|zh-hant)(?:\/(.*?))?\/?$/);return m&&pages.includes(m[2]||'')?{locale:m[1],page:m[2]||''}:path==='/'?{locale:'en',page:''}:null;}
