import {useEffect,useMemo,useState} from 'react';
import context from '../data/market-context.json';
import macroSeries from '../data/macro-series.json';
import {macroIndicators} from './research-path-data.mjs';
import {ETFS} from './etf-catalog.mjs';

const colors=['#08775f','#2364aa','#a74715','#773a98','#525e10','#b75d69','#167c80','#8b6f27'];
function MiniTrend({rows,label,field='value'}:{rows:any[];label:string;field?:string}){const values=(rows||[]).slice(-36).filter(x=>Number.isFinite(Number(x[field])));if(values.length<2)return null;const lo=Math.min(...values.map(x=>Number(x[field]))),hi=Math.max(...values.map(x=>Number(x[field]))),range=hi-lo||1;return <svg className="eq-mini-trend" viewBox="0 0 220 58" role="img" aria-label={label}><polyline fill="none" stroke="currentColor" strokeWidth="2" points={values.map((r,i)=>String(4+i*212/Math.max(1,values.length-1))+','+String(52-(Number(r[field])-lo)/range*44)).join(' ')}/></svg>}
function ReturnChart({series,locale}:{series:any[];locale:string}){
 const zh=locale==='zh-hant',allDates=[...new Set(series.flatMap(s=>s.points.map((p:any)=>p.date)))].sort();
 if(allDates.length<2)return null;
 const values=series.flatMap(s=>s.points.map((p:any)=>p.value)),lo=Math.min(...values),hi=Math.max(...values),span=hi-lo||1;
 const x=(date:string)=>60+(allDates.indexOf(date)/Math.max(1,allDates.length-1))*600,y=(v:number)=>235-(v-lo)/span*190;
 return <svg className="eq-benchmark-chart" viewBox="0 0 700 270" role="img" aria-label={zh?'相對基準調整後價格比較':'Adjusted-price comparison against benchmark'}><line x1="60" y1="35" x2="60" y2="235" stroke="#8ba9a2"/><line x1="60" y1="235" x2="660" y2="235" stroke="#8ba9a2"/>{series.map((s,si)=><g key={s.symbol}>{s.points.map((p:any,i:number)=>{const prev=s.points[i-1];return <g key={p.date}>{prev&&<line x1={x(prev.date)} y1={y(prev.value)} x2={x(p.date)} y2={y(p.value)} stroke={colors[si]} strokeWidth="2"/>}<circle cx={x(p.date)} cy={y(p.value)} r="3" fill={colors[si]}><title>{s.symbol} {p.date}: {p.value.toFixed(2)}</title></circle></g>})}</g>)}<text x="60" y="258" fontSize="11">{allDates[0]}</text><text x="565" y="258" fontSize="11">{allDates[allDates.length-1]}</text></svg>;
}

export function ResearchContextComparison({locale,full,symbols,benchmark,onBenchmark,macroIds,onMacroIds}:{locale:string;full:boolean;symbols:string[];benchmark:string;onBenchmark:(v:string)=>void;macroIds:string[];onMacroIds:(v:string[])=>void}){
 const zh=locale==='zh-hant',t=(en:string,cn:string)=>zh?cn:en,[market,setMarket]=useState<any>(null),[failed,setFailed]=useState(false);
 const benchmarks=ETFS;
 const macroOptions=macroIndicators.filter(x=>x.value!==null);
 const h10=(context.sources as any).h10,lastFx=h10?.rows?.at(-1);
 useEffect(()=>{if(!full){setMarket(null);return;}const selected=[...new Set([...symbols,benchmark])].slice(0,9);if(!selected.length){setMarket(null);return;}const ac=new AbortController();setFailed(false);fetch('/api/research-benchmark?symbols='+encodeURIComponent(selected.join(',')),{signal:ac.signal}).then(async r=>{if(!r.ok)throw Error();return r.json()}).then(setMarket).catch(e=>{if(e.name!=='AbortError')setFailed(true)});return()=>ac.abort()},[full,benchmark,symbols.join(',')]);
 const comparison=useMemo(()=>{const rows=market?.rows||[],group:any={};for(const r of rows)(group[r.symbol]??=[]).push(r);for(const s of Object.keys(group))group[s].sort((a:any,b:any)=>a.session_date.localeCompare(b.session_date));const wanted=[...new Set([...symbols,benchmark])].filter(s=>group[s]?.length>1);if(wanted.length<2)return {series:[],currencyMismatch:false};const currencies=new Set(wanted.flatMap(s=>group[s].map((r:any)=>r.currency).filter(Boolean)));if(currencies.size>1)return {series:[],currencyMismatch:true};let dates=group[wanted[0]].map((r:any)=>r.session_date);for(const s of wanted.slice(1)){const set=new Set(group[s].map((r:any)=>r.session_date));dates=dates.filter((d:string)=>set.has(d));}if(dates.length<2)return {series:[],currencyMismatch:false};return {series:wanted.map(symbol=>{const by=new Map(group[symbol].map((r:any)=>[r.session_date,Number(r.adjusted_close)])),base=Number(by.get(dates[0]));return {symbol,points:dates.map((date:string)=>({date,value:Number(by.get(date))/base*100}))};}),currencyMismatch:false};},[market,symbols.join(','),benchmark]);
 const normalized=comparison.series;
 const toggleMacro=(id:string)=>onMacroIds(macroIds.includes(id)?macroIds.filter(x=>x!==id):macroIds.length>=6?macroIds:[...macroIds,id]);
 const selectedMacro=macroOptions.filter(x=>macroIds.includes(x.id));
 const fund=ETFS.find(f=>f.symbol===benchmark);
 return <section id="market-context" className="eq-section eq-context-section"><div className="eq-section-heading"><div><h2>{t('Benchmark & economic context','市場基準與經濟背景比較')}</h2><p>{t('Keep operating results, market performance and macro context separate, but view them in the same research scope.','把公司營運、行情表現與總經背景分開計算，但放在同一個研究範圍一起看。')}</p></div></div>
 <div className="eq-controls"><label>{t('Market / sector benchmark ETF','市場／產業基準 ETF')}<select value={benchmark} onChange={e=>onBenchmark(e.target.value)}>{benchmarks.map(f=><option key={f.symbol} value={f.symbol}>{f.symbol} · {f.name}</option>)}</select></label><a className="btn" href={'/'+locale+'/macro/'}>{t('Open macro page','查看完整總經')} →</a></div>
 {fund&&<div className="eq-benchmark-card"><div><span className="eyebrow">BENCHMARK</span><strong>{fund.symbol} · {fund.name}</strong><small>{fund.scope[zh?'zh-hant':'en']} · {t('Tracks','追蹤')} {fund.benchmark}</small></div><div><strong>{fund.expense===null?'—':fund.expense.toFixed(2)+'%'}</strong><small>{t('Expense ratio','費用率')}</small></div></div>}
 <fieldset className="eq-macro-picker"><legend>{t('Economic context (choose up to 6)','經濟背景（最多選 6 項）')}</legend>{macroOptions.map(x=><label key={x.id}><input type="checkbox" checked={macroIds.includes(x.id)} disabled={!macroIds.includes(x.id)&&macroIds.length>=6} onChange={()=>toggleMacro(x.id)}/>{x.label[zh?'zh-hant':'en']}</label>)}</fieldset>
 <div className="eq-context-grid">{selectedMacro.map(x=>{const trend=(macroSeries as any).series?.find((s:any)=>s.id===x.id),latest=trend?.rows?.at(-1);return <article key={x.id}><span>{x.market}</span><strong>{x.label[zh?'zh-hant':'en']}</strong><b>{latest?Number(latest.value).toFixed(2):String(x.value)}{x.unit}</b>{trend&&<MiniTrend rows={trend.rows} label={x.label[zh?'zh-hant':'en']}/>}<small>{latest?latest.date:x.period} · {trend?'BLS Public Data API':x.source}</small></article>})}{lastFx&&<article><span>FX</span><strong>USD/TWD</strong><b>{Number(lastFx.usdTwd).toFixed(2)}</b><MiniTrend rows={h10?.rows||[]} field="usdTwd" label="USD/TWD"/><small>{lastFx.date} · Federal Reserve H.10</small></article>}</div>
 <p className="eq-meta">{(macroSeries as any).retrievedAt?t('CPI and unemployment trend cards use automatically refreshed official BLS monthly series; other macro cards remain dated snapshots until their historical series are connected.','CPI 與失業率趨勢卡使用自動更新的 BLS 官方月資料；其他總經項目在歷史序列接入前仍以具日期快照呈現。'):t('Historical CPI and unemployment trend ingestion is configured and awaiting its first successful official-source refresh.','CPI 與失業率歷史趨勢的官方資料同步已設定，正在等待第一次成功更新。')}</p>
 <div className="eq-market-comparison"><h3>{t('Market performance comparison','市場表現比較')}</h3>{!full?<p>{t('Research / Pro access is required for account-level benchmark comparison.','帳號層級的大盤比較需 Research／Pro。')}</p>:failed?<p role="alert">{t('Benchmark data status could not be loaded.','大盤比較資料狀態目前無法讀取。')}</p>:comparison.currencyMismatch?<div className="eq-data-gap"><strong>{t('The selected benchmark uses a different trading currency.','所選基準與比較標的使用不同交易幣別。')}</strong><p>{t('QuantPath will not compare the normalized lines until aligned FX conversion is available; choose a same-currency benchmark or review currency exposure separately.','在匯率轉換序列完整對齊前，QuantPath 不會直接比較正規化走勢；請改選相同幣別基準，或分開研究匯率曝險。')}</p></div>:normalized.length>=2?<><ReturnChart series={normalized} locale={locale}/><div className="eq-selection-summary">{normalized.map((s:any,i:number)=><span key={s.symbol} style={{borderColor:colors[i]}}>{s.symbol}</span>)}</div><p className="eq-meta">{t('Series are rebased to 100 on their first common approved session. This is an adjusted-price research series, not a guaranteed total-return calculation; verify source adjustment methodology before interpreting dividends.','各序列以第一個共同且核准的交易日重設為 100。這是調整後價格研究序列，不保證等同總報酬；解讀股息前請確認來源的調整方法。')}</p></>:<div className="eq-data-gap"><strong>{t('Benchmark comparison is ready in the interface, but approved aligned market history is not yet available.','大盤比較介面已完成，但目前尚無足夠「已核准且期間對齊」的市場歷史資料。')}</strong><p>{t('QuantPath will not fill this gap with an unlicensed quote feed or synthetic returns. When approved market history is connected, the selected companies and benchmark will populate here automatically.','QuantPath 不會用未授權行情或合成報酬補空缺。合法且核准的歷史行情接入後，上方已選公司與大盤會自動在這裡比較。')}</p></div>}</div>
 <p className="eq-meta">{t('Macro cards are dated context snapshots, not same-period regressors for company annual results. Do not infer causality from proximity on this page.','總經卡片是具日期的背景快照，不等於與公司年度財報同期間的迴歸變數；不能因同頁呈現就推論因果。')}</p></section>;
}