import {useState} from 'react';
import {footballScenario} from './sports-engine.mjs';
import './lottery-tools.css';
export function SportsAnalysis({locale}:{locale?:string}){
 const [localEnglish,setEn]=useState(true),en=locale?locale==='en':localEnglish;const [home,setHome]=useState('1.5'),[away,setAway]=useState('1.0');
 const t=(zh:string,english:string)=>en?english:zh;
 const valid=home.trim()!==''&&away.trim()!==''&&[Number(home),Number(away)].every(n=>Number.isFinite(n)&&n>=0&&n<=6);
 const r=valid?footballScenario(Number(home),Number(away)):null;
 return <div className="lottery-tools" lang={en?'en':'zh-Hant'}><div className="page-heading"><div><div className="eyebrow">SPORTS RESEARCH · EDUCATIONAL SCENARIOS</div><h1>{t('運動分析：先理解模型，再檢視證據。','Sports research: understand the model and examine the evidence.')}</h1><p>{t('足球情境工具已開放；真實賽事、賠率與經驗證的預測尚未接入。','The football scenario tool is available. Live events, odds and validated forecasts are not connected.')}</p></div>{!locale&&<button className="btn" onClick={()=>setEn(v=>!v)}>{en?'繁體中文':'English'}</button>}</div>
 <aside className="callout" style={{display:'block'}} aria-label={t('使用提醒','Use notice')}><strong>{t('僅供統計研究與教育，不提供投注服務。','Statistical research and education only. No betting service.')}</strong><p>{t('本工具不是投注建議，不保證中獎、獲利或任何賽果。勿借貸、追損或挪用生活費投注。未成年人不得購買或兌領運動彩券。','This tool is not betting advice and does not guarantee wins, profits or match outcomes. Do not borrow, chase losses or use essential living funds to gamble. Minors must not purchase or redeem Taiwan sports lottery tickets.')}</p><p>{t('QuantPath Labs 為獨立研究網站，非運彩發行或銷售機構，亦非官方合作平台。','QuantPath Labs is an independent research website, not a sports lottery issuer, retailer or official partner.')}</p></aside>
 <section className="panel"><div className="panel-head"><div><h2>{t('足球進球情境計算器','Football goal scenario calculator')}</h2><p>{t('使用者假設值 · 非真實球隊資料 · 未訓練的 Poisson 教學模型','User assumptions · No real team data · Unfitted Poisson teaching model')}</p></div></div><div className="panel-body"><p>{t('調整兩隊的預期進球平均值，觀察假設改變如何影響勝、和、負分布。預設 1.5 與 1.0 純為示例，並非從比賽資料估計。','Adjust each team’s assumed expected goals to explore the resulting win, draw and loss distribution. Defaults of 1.5 and 1.0 are illustrative, not estimated from match data.')}</p><div className="tool-fields spaced"><label>{t('主隊假設預期進球（0–6）','Assumed home goals (0–6)')}<input type="number" min="0" max="6" step="0.1" value={home} onChange={e=>setHome(e.target.value)}/></label><label>{t('客隊假設預期進球（0–6）','Assumed away goals (0–6)')}<input type="number" min="0" max="6" step="0.1" value={away} onChange={e=>setAway(e.target.value)}/></label><button className="btn" onClick={()=>{setHome('1.5');setAway('1.0')}}>{t('重設示例','Reset example')}</button></div>{!r?<p role="alert">{t('兩個欄位都必須填入 0 至 6 的有效數值。','Both fields require a valid number from 0 to 6.')}</p>:<div aria-live="polite"><h3>{t('假設情境結果 — 非實際賽事預測','Hypothetical results — not a match forecast')}</h3><div className="dimension-grid spaced">{[[t('主勝','Home win'),r.win],[t('和局','Draw'),r.draw],[t('客勝','Away win'),r.loss]].map(([label,p])=><div className="dimension-card" key={String(label)}><h3>{label}</h3><strong style={{fontSize:28}}>{(Number(p)*100).toFixed(1)}%</strong></div>)}</div><div className="table-wrap spaced"><table className="data-table" style={{width:'100%'}}><caption>{t('模型中機率最高的六個比分情境；不是選賽推薦','Six highest-probability score scenarios in this model; not betting picks')}</caption><thead><tr><th>{t('主隊：客隊','Home : Away')}</th><th>{t('情境機率','Scenario probability')}</th></tr></thead><tbody>{r.scores.map((s:any)=><tr key={s.home+':'+s.away}><td>{s.home} : {s.away}</td><td>{(s.p*100).toFixed(2)}%</td></tr>)}</tbody></table></div><p className="small">{t('各機率以相同假設計算，四捨五入後合計可能略有差異。結果不會儲存為會員預測或投注紀錄。','Probabilities use the same assumptions; rounded values may not sum exactly. Results are not saved as member forecasts or betting records.')}</p></div>}</div></section>
 <section className="panel"><div className="panel-body"><h2>{t('方法與適用範圍','Method and scope')}</h2><p className="spaced">{t('版本：football-poisson-education-v1。假設兩隊進球互相獨立，且各隊的進球數服從固定平均值的 Poisson 分布。計算一般正規時間（含補時），不含延長賽與點球大戰；不處理取消、腰斬或投注結算。','Version: football-poisson-education-v1. Goals are assumed independent, each following a Poisson distribution with a fixed mean. The scenario concerns regulation time including stoppage time, excluding extra time and shootouts. It does not handle cancellations, abandonment or bet settlement.')}</p><p className="spaced">{t('此模型沒有考慮陣容、傷病、紅牌、賽程及進球相關性。沒有訓練資料、回測績效或校準證據，因此不能把輸出當作真實賽事勝率。','The model omits lineups, injuries, red cards, schedules and goal dependence. There is no training dataset, backtest performance or calibration evidence, so its output must not be treated as real match probabilities.')}</p><p className="spaced">{t('真實資料接入前，需確認來源使用與公開展示權、賽事及時間對照、資料新鮮度，再進行時間順序驗證。現在沒有可搜尋的真實賽事，沒有賠率比較，也沒有自動下注。','Before real data is enabled, source use and display rights, event/time mapping and freshness must be verified, followed by chronological model evaluation. Real event search, odds comparison and automated wagering are not available.')}</p></div></section>
 <section className="panel"><div className="panel-body"><h2>{t('責任使用與法規資訊','Responsible use and legal information')}</h2><p className="spaced">{t('本站不銷售、代購、代收投注款、兌獎或仲介投注，也不提供博彩導流或保證獲利服務。警語不是營運許可，也不保證任何功能在所有地區合法。所在地另有較嚴規定時，應遵守當地規定。','This site does not sell tickets, place bets, collect stakes, pay prizes, broker wagering or provide gambling referrals or guaranteed returns. Notices are not operating licences or assurances of legality in every jurisdiction. Stricter local requirements still apply.')}</p><p className="spaced">{t('如投注已影響生活、財務或情緒，請停止投注，向可信任的人或合格心理健康專業人員尋求協助。','If gambling affects your daily life, finances or wellbeing, stop and seek support from someone you trust or a qualified mental-health professional.')}</p><p className="spaced"><a className="text-link" href="https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=H0120050" target="_blank" rel="noreferrer">{t('台灣《運動彩券發行條例》：第 4、11、13 條 ↗','Taiwan Sports Lottery Issuance Act: Articles 4, 11 and 13 ↗')}</a></p><p className="small">{t('法規來源檢視日：2026-09-20。以上為服務範圍與一般資訊，非個別法律意見；跨地區或商業功能擴充前須另行確認適用規範。','Legal source reviewed: 2026-09-20. This describes service scope and general information, not individual legal advice. Applicable rules must be reviewed before regional or commercial expansion.')}</p></div></section></div>;
}
