export const workspaceCopy={
 en:{
 'workspace.title':'Workspace','workspace.home':'Research overview','workspace.equities':'Stocks & ETFs','workspace.lottery':'FREE LOTTERY TOOLS','workspace.analysis':'Historical analysis','workspace.planner':'Lottery plans','workspace.records':'Lottery spending & prizes','workspace.sports':'Sports methods','workspace.methods':'METHODS & ADMIN','workspace.lab':'Model laboratory','workspace.admin':'Administration','workspace.plans':'Membership plans','workspace.public':'Public website','workspace.verified':'Email verified','workspace.demo':'Demo · synthetic records','workspace.local':'Stored in this browser','workspace.logout':'Sign out','workspace.menu':'Open navigation','workspace.language':'Workspace language','workspace.scope':'Lottery analysis, planning and administration currently use Traditional Chinese. Your saved values and notes stay unchanged.','workspace.disclaimer':'Historical results do not guarantee winnings or investment returns.','workspace.demoNotice':'Demo personal records and model results are synthetic. Complete lottery tools require a verified free account. Demo access does not grant paid privileges.',
 'status.loading':'Loading…','status.error':'Unable to load your account data. No balance or record count has been inferred.','status.retry':'Try again','status.unknown':'Plan unavailable','status.demo':'Demo access','status.sales':'Subscriptions are not open. No charges or automatic upgrades.','status.expiry':'Access until','status.canceling':'Renewal canceled; access lasts until the paid period ends.',
 'overview.title':'Your research, in one workspace.','overview.sub':'Compare company facts, review source evidence and keep your own records.','overview.research':'Stock & ETF research','overview.researchSub':'50 AI-related companies · 14 financial dimensions. Full tools require active Research or Pro access.','overview.preview':'Open stock preview','overview.full':'Open research tools','overview.free':'Free verified membership includes all three Taiwan lottery tools.','overview.lotterySub':'Historical analysis, saved plans and actual spending records. Generating numbers is not a purchase.','overview.records':'Open spending records','overview.account':'Your membership','overview.sources':'Data freshness','overview.sourceHint':'Snapshot retrieval time, not real-time prices or database synchronization time.','overview.method':'News, attention & AI','overview.methodSub':'Official source observations are separate from social attention. Missing data is not zero; unreleased models cannot issue AI signals.',
 'records.title':'Lottery spending & prizes','records.sub':'Record actual spending and prizes separately. Saved number combinations do not create purchases.','records.add':'Add record','records.export':'Export CSV','records.month':'Record month','records.game':'Lottery game','records.allMonths':'All months','records.allGames':'All games','records.clear':'Clear filters','records.empty':'No spending records yet','records.emptySub':'Add an actual transaction when you have one. No purchase or prize is inferred from generated numbers.','records.filtered':'No records match these filters','records.filteredSub':'Your existing records are unchanged. Clear filters to see them.','records.actualCost':'Actual spending','records.actualPrize':'Actual prize','records.cost':'Filtered spending','records.prize':'Filtered prizes','records.net':'Net result','records.detail':'Your records','records.date':'Date','records.note':'Note','records.action':'Action','records.delete':'Delete record','records.confirm':'Delete this record?','records.warning':'This removes the record and recalculates totals. Deletion cannot be undone.','records.keep':'Keep record','records.unit':'TWD','records.count':'records','records.save':'Save record','records.saving':'Saving…','records.dialogSub':'Enter actual spending only. If no prize has been received, enter 0 for the prize.','records.invalid':'Enter a valid date and whole amounts. Spending must be greater than 0.','records.noteHint':'For example, draw number or redemption status','records.saved':'Record saved','records.deleted':'Record deleted','game.lotto':'Lotto 6/49','game.power':'Super Lotto 6/38','game.daily':'Daily Cash 539'
 },
 'zh-hant':{
 'workspace.title':'會員工作台','workspace.home':'研究總覽','workspace.equities':'股票與 ETF','workspace.lottery':'免費樂透工具','workspace.analysis':'歷史開獎分析','workspace.planner':'樂透規劃','workspace.records':'樂透收支紀錄','workspace.sports':'運動研究方法','workspace.methods':'研究方法與管理','workspace.lab':'模型實驗室','workspace.admin':'管理後台','workspace.plans':'會員方案','workspace.public':'公開首頁','workspace.verified':'Email 已驗證','workspace.demo':'示範 · 合成紀錄','workspace.local':'僅儲存在此瀏覽器','workspace.logout':'登出','workspace.menu':'開啟導覽','workspace.language':'工作台語言','workspace.scope':'樂透分析、規劃與管理功能目前使用繁體中文。既有資料值與個人備註不會因切換語言而改變。','workspace.disclaimer':'歷史結果不保證中獎或投資報酬。','workspace.demoNotice':'示範個人紀錄與模型結果為合成資料。完整樂透工具須驗證免費帳號；示範模式不會開通付費權益。',
 'status.loading':'載入中…','status.error':'無法讀取帳號資料，未推定餘額或紀錄筆數。','status.retry':'重試','status.unknown':'方案狀態讀取失敗','status.demo':'示範權益','status.sales':'訂閱尚未開放，不會扣款或自動升級。','status.expiry':'可使用至','status.canceling':'已取消續訂，可使用至已付費期限結束。',
 'overview.title':'在同一個工作台，接續你的研究。','overview.sub':'比較公司事實、核對資料來源，並保留自己的紀錄。','overview.research':'股票與 ETF 研究','overview.researchSub':'50 家 AI 相關公司 · 14 個財務維度。完整工具需有效 Research 或 Pro 權益。','overview.preview':'開啟股票預覽','overview.full':'開啟研究工具','overview.free':'Email 驗證後，免費使用台灣三彩種完整工具。','overview.lotterySub':'歷史分析、儲存規劃與實際收支。產生號碼不等於購買。','overview.records':'查看收支紀錄','overview.account':'我的會員方案','overview.sources':'資料新鮮度','overview.sourceHint':'此為快照擷取時間，不是即時股價或資料庫同步時間。','overview.method':'新聞、聲量與 AI','overview.methodSub':'官方來源觀測與社群聲量分開呈現。缺資料不當作 0；未發布模型不會產生 AI 訊號。',
 'records.title':'樂透收支紀錄','records.sub':'分開記錄實際支出與獎金。儲存號碼組合不會新增購買紀錄。','records.add':'新增紀錄','records.export':'匯出 CSV','records.month':'紀錄月份','records.game':'彩種','records.allMonths':'所有月份','records.allGames':'所有彩種','records.clear':'清除篩選','records.empty':'尚未建立收支紀錄','records.emptySub':'有實際收支時再新增。系統不會把產生號碼當成購買或中獎。','records.filtered':'沒有符合篩選條件的紀錄','records.filteredSub':'既有紀錄未變更；清除篩選即可重新查看。','records.actualCost':'實際支出','records.actualPrize':'實際獎金','records.cost':'篩選後支出','records.prize':'篩選後獎金','records.net':'淨結果','records.detail':'收支明細','records.date':'日期','records.note':'備註','records.action':'操作','records.delete':'刪除紀錄','records.confirm':'刪除這筆紀錄？','records.warning':'刪除後將重新計算總額，此操作無法復原。','records.keep':'保留紀錄','records.unit':'新台幣','records.count':'筆紀錄','records.save':'儲存紀錄','records.saving':'儲存中…','records.dialogSub':'只填寫實際支出；尚未收到獎金時，獎金可先填 0。','records.invalid':'請填寫有效日期與整數金額；支出需大於 0。','records.noteHint':'例如：期別、兌獎狀態','records.saved':'紀錄已儲存','records.deleted':'紀錄已刪除','game.lotto':'大樂透','game.power':'威力彩','game.daily':'今彩539'
 }
};
export const workspaceText=(locale,key)=>workspaceCopy[locale==='zh-hant'?'zh-hant':'en'][key]??workspaceCopy.en[key]??key;
export const workspaceTitle=(locale,view)=>workspaceText(locale,`workspace.${({dashboard:'home',records:'records'})[view]||view}`);
export function filteredRecords(records,month,game){return records.filter(r=>(month==='all'||r.date.startsWith(month))&&(game==='all'||r.game===game)).sort((a,b)=>b.date.localeCompare(a.date));}
export function recordsCSV(records,locale){const t=k=>workspaceText(locale,k),safe=s=>'"'+(typeof s==='string'&&/^[=+\-@\t\r]/.test(s)?"'"+s:String(s)).replaceAll('"','""')+'"';return '\uFEFF'+['date','game','cost','prize','net','note'].map(k=>safe(t('records.'+k))).join(',')+'\n'+records.map(r=>[r.date,t('game.'+r.game),r.cost,r.prize,r.prize-r.cost,r.note].map(safe).join(',')).join('\n');}
